const CHARACTERS = [
  // ─── JEDI (46) ─────────────────────────────────────────────────────────────
  { id: "aayla_secura", name: "Aayla Secura", category: "Jedi", dlc: null, img: "Character images/aayla_secura.png" },
  { id: "anakin_skywalker_ep2_cape", name: "Anakin Skywalker (Episode II - Cape)", category: "Jedi", dlc: null, img: "Character images/anakin_skywalker_ep2_cape.png" },
  { id: "anakin_skywalker_ep2", name: "Anakin Skywalker (Episode II)", category: "Jedi", dlc: null, img: "Character images/anakin_skywalker_ep2.png" },
  { id: "anakin_skywalker_ep3_cape", name: "Anakin Skywalker (Episode III - Cape)", category: "Jedi", dlc: null, img: "Character images/anakin_skywalker_ep3_cape.png" },
  { id: "anakin_skywalker_ep3", name: "Anakin Skywalker (Episode III)", category: "Jedi", dlc: null, img: "Character images/anakin_skywalker_ep3.png" },
  { id: "barriss_offee", name: "Barriss Offee", category: "Jedi", dlc: null, img: "Character images/barriss_offee.png" },
  { id: "ben_solo", name: "Ben Solo", category: "Jedi", dlc: null, img: "Character images/ben_solo.png" },
  { id: "jocasta_nu", name: "Jocasta Nu", category: "Jedi", dlc: null, img: "Character images/jocasta_nu.png" },
  { id: "ki_adi_mundi", name: "Ki-Adi Mundi", category: "Jedi", dlc: null, img: "Character images/ki_adi_mundi.png" },
  { id: "kit_fisto", name: "Kit Fisto", category: "Jedi", dlc: null, img: "Character images/kit_fisto.png" },
  { id: "leia_training_flashback", name: "Leia (Training Flashback)", category: "Jedi", dlc: null, img: "Character images/leia_training_flashback.png" },
  { id: "luke_skywalker_old_flashback", name: "Luke Skywalker (Old - Flashback)", category: "Jedi", dlc: null, img: "Character images/luke_skywalker_old_flashback.png" },
  { id: "luke_skywalker_old_crait", name: "Luke Skywalker (Old - Crait)", category: "Jedi", dlc: null, img: "Character images/luke_skywalker_old_crait.png" },
  { id: "luke_skywalker_ep5_no_jacket", name: "Luke Skywalker (Episode V - No Jacket)", category: "Jedi", dlc: null, img: "Character images/luke_skywalker_ep5_no_jacket.png" },
  { id: "luke_skywalker_hoth", name: "Luke Skywalker (Hoth)", category: "Jedi", dlc: null, img: "Character images/luke_skywalker_hoth.png" },
  { id: "luke_skywalker_jabbas_palace", name: "Luke Skywalker (Jabba's Palace)", category: "Jedi", dlc: null, img: "Character images/luke_skywalker_jabbas_palace.png" },
  { id: "luke_skywalker_training_flashback", name: "Luke Skywalker (Training Flashback)", category: "Jedi", dlc: null, img: "Character images/luke_skywalker_training_flashback.png" },
  { id: "luke_skywalker_ep5_jedi", name: "Luke Skywalker (Episode V - Jedi)", category: "Jedi", dlc: null, img: "Character images/luke_skywalker_ep5_jedi.png" },
  { id: "luke_skywalker_endor", name: "Luke Skywalker (Endor)", category: "Jedi", dlc: null, img: "Character images/luke_skywalker_endor.png" },
  { id: "luke_skywalker_ep6", name: "Luke Skywalker (Episode VI)", category: "Jedi", dlc: null, img: "Character images/luke_skywalker_ep6.png" },
  { id: "luke_skywalker_yoda_backpack", name: "Luke Skywalker (Yoda Backpack)", category: "Jedi", dlc: null, img: "Character images/luke_skywalker_yoda_backpack.png" },
  { id: "luminara_unduli", name: "Luminara Unduli", category: "Jedi", dlc: null, img: "Character images/luminara_unduli.png" },
  { id: "mace_windu_cape", name: "Mace Windu (Cape)", category: "Jedi", dlc: null, img: "Character images/mace_windu_cape.png" },
  { id: "mace_windu", name: "Mace Windu", category: "Jedi", dlc: null, img: "Character images/mace_windu.png" },
  { id: "obi_wan_kenobi_ep3", name: "Obi-Wan Kenobi (Episode III)", category: "Jedi", dlc: null, img: "Character images/obi_wan_kenobi_ep3.png" },
  { id: "obi_wan_kenobi_ep3_cape", name: "Obi-Wan Kenobi (Episode III - Cape)", category: "Jedi", dlc: null, img: "Character images/obi_wan_kenobi_ep3_cape.png" },
  { id: "obi_wan_kenobi_ep1", name: "Obi-Wan Kenobi (Episode I)", category: "Jedi", dlc: null, img: "Character images/obi_wan_kenobi_ep1.png" },
  { id: "obi_wan_kenobi_ep1_no_cape", name: "Obi-Wan Kenobi (Episode I - No Cape)", category: "Jedi", dlc: null, img: "Character images/obi_wan_kenobi_ep1_no_cape.png" },
  { id: "obi_wan_kenobi_ep2", name: "Obi-Wan Kenobi (Episode II)", category: "Jedi", dlc: null, img: "Character images/obi_wan_kenobi_ep2.png" },
  { id: "obi_wan_kenobi_ep2_robe", name: "Obi-Wan Kenobi (Episode II - Robe)", category: "Jedi", dlc: null, img: "Character images/obi_wan_kenobi_ep2_robe.png" },
  { id: "old_ben_kenobi_tatooine_hood", name: "Old Ben Kenobi (Tatooine - Hood)", category: "Jedi", dlc: null, img: "Character images/old_ben_kenobi_tatooine_hood.png" },
  { id: "old_ben_kenobi_tatooine", name: "Old Ben Kenobi (Tatooine)", category: "Jedi", dlc: null, img: "Character images/old_ben_kenobi_tatooine.png" },
  { id: "plo_koon", name: "Plo Koon", category: "Jedi", dlc: null, img: "Character images/plo_koon.png" },
  { id: "qui_gon_jinn_cape", name: "Qui-Gon Jinn (Cape)", category: "Jedi", dlc: null, img: "Character images/qui_gon_jinn_cape.png" },
  { id: "qui_gon_jinn_tatooine_disguise", name: "Qui-Gon Jinn (Tatooine Disguise)", category: "Jedi", dlc: null, img: "Character images/qui_gon_jinn_tatooine_disguise.png" },
  { id: "qui_gon_jinn", name: "Qui-Gon Jinn", category: "Jedi", dlc: null, img: "Character images/qui_gon_jinn.png" },
  { id: "rey_kijimi_coat", name: "Rey (Kijimi Coat)", category: "Jedi", dlc: null, img: "Character images/rey_kijimi_coat.png" },
  { id: "rey_ep7_jedi", name: "Rey (Episode VII - Jedi)", category: "Jedi", dlc: null, img: "Character images/rey_ep7_jedi.png" },
  { id: "rey_ep9", name: "Rey (Episode IX)", category: "Jedi", dlc: null, img: "Character images/rey_ep9.png" },
  { id: "rey_skywalker", name: "Rey Skywalker", category: "Jedi", dlc: null, img: "Character images/rey_skywalker.png" },
  { id: "rey_grey_jedi_wrap", name: "Rey (Grey Jedi Wrap)", category: "Jedi", dlc: null, img: "Character images/rey_grey_jedi_wrap.png" },
  { id: "shaak_ti", name: "Shaak Ti", category: "Jedi", dlc: null, img: "Character images/shaak_ti.png" },
  { id: "yaddle", name: "Yaddle", category: "Jedi", dlc: null, img: "Character images/yaddle.png" },
  { id: "yarael_poof", name: "Yarael Poof", category: "Jedi", dlc: null, img: "Character images/yarael_poof.png" },
  { id: "yoda", name: "Yoda", category: "Jedi", dlc: null, img: "Character images/yoda.png" },

  // ─── HEROES (87) ────────────────────────────────────────────────────────────
  { id: "admiral_ackbar", name: "Admiral Ackbar", category: "Hero", dlc: null, img: "Character images/admiral_ackbar.png" },
  { id: "admiral_holdo", name: "Admiral Holdo", category: "Hero", dlc: null, img: "Character images/admiral_holdo.png" },
  { id: "aftab_ackbar", name: "Aftab Ackbar", category: "Hero", dlc: null, img: "Character images/aftab_ackbar.png" },
  { id: "bail_organa", name: "Bail Organa", category: "Hero", dlc: null, img: "Character images/bail_organa.png" },
  { id: "beaumont_kin", name: "Beaumont Kin", category: "Hero", dlc: null, img: "Character images/beaumont_kin.png" },
  { id: "biggs_darklighter", name: "Biggs Darklighter", category: "Hero", dlc: null, img: "Character images/biggs_darklighter.png" },
  { id: "boolio", name: "Boolio", category: "Hero", dlc: null, img: "Character images/boolio.png" },
  { id: "boss_nass", name: "Boss Nass", category: "Hero", dlc: null, img: "Character images/boss_nass.png" },
  { id: "cai_threnalli", name: "C'ai Threnalli", category: "Hero", dlc: null, img: "Character images/cai_threnalli.png" },
  { id: "captain_antilles", name: "Captain Antilles", category: "Hero", dlc: null, img: "Character images/captain_antilles.png" },
  { id: "captain_panaka", name: "Captain Panaka", category: "Hero", dlc: null, img: "Character images/captain_panaka.png" },
  { id: "captain_tarpals", name: "Captain Tarpals", category: "Hero", dlc: null, img: "Character images/captain_tarpals.png" },
  { id: "captain_typho", name: "Captain Typho", category: "Hero", dlc: null, img: "Character images/captain_typho.png" },
  { id: "clone_trooper_phase1", name: "Clone Trooper (Phase I)", category: "Hero", dlc: null, img: "Character images/clone_trooper_phase1.png" },
  { id: "clone_trooper_commander", name: "Clone Trooper (Commander)", category: "Hero", dlc: null, img: "Character images/clone_trooper_commander.png" },
  { id: "clone_trooper_captain", name: "Clone Trooper (Captain)", category: "Hero", dlc: null, img: "Character images/clone_trooper_captain.png" },
  { id: "clone_trooper_lieutenant", name: "Clone Trooper (Lieutenant)", category: "Hero", dlc: null, img: "Character images/clone_trooper_lieutenant.png" },
  { id: "clone_trooper_sergeant", name: "Clone Trooper (Sergeant)", category: "Hero", dlc: null, img: "Character images/clone_trooper_sergeant.png" },
  { id: "clone_trooper_phase2", name: "Clone Trooper (Phase II)", category: "Hero", dlc: null, img: "Character images/clone_trooper_phase2.png" },
  { id: "clone_trooper_501st", name: "Clone Trooper (501st Legion)", category: "Hero", dlc: null, img: "Character images/clone_trooper_501st.png" },
  { id: "clone_trooper_coruscant_guard", name: "Clone Trooper (Coruscant Guard)", category: "Hero", dlc: null, img: "Character images/clone_trooper_coruscant_guard.png" },
  { id: "clone_trooper_212th", name: "Clone Trooper (212th Attack Battalion)", category: "Hero", dlc: null, img: "Character images/clone_trooper_212th.png" },
  { id: "clone_trooper_kashyyyk", name: "Clone Trooper (Kashyyyk)", category: "Hero", dlc: null, img: "Character images/clone_trooper_kashyyyk.png" },
  { id: "commander_cody", name: "Commander Cody", category: "Hero", dlc: null, img: "Character images/commander_cody.png" },
  { id: "commander_dacy", name: "Commander D'Acy", category: "Hero", dlc: null, img: "Character images/commander_dacy.png" },
  { id: "commander_gree", name: "Commander Gree", category: "Hero", dlc: null, img: "Character images/commander_gree.png" },
  { id: "ello_asty", name: "Ello Asty", category: "Hero", dlc: null, img: "Character images/ello_asty.png" },
  { id: "finn_ep7", name: "Finn (Episode VII)", category: "Hero", dlc: null, img: "Character images/finn_ep7.png" },
  { id: "finn_bacta_suit", name: "Finn (Bacta Suit)", category: "Hero", dlc: null, img: "Character images/finn_bacta_suit.png" },
  { id: "finn_crait", name: "Finn (Crait)", category: "Hero", dlc: null, img: "Character images/finn_crait.png" },
  { id: "finn_ep9", name: "Finn (Episode IX)", category: "Hero", dlc: null, img: "Character images/finn_ep9.png" },
  { id: "finn_kijimi_coat", name: "Finn (Kijimi Coat)", category: "Hero", dlc: null, img: "Character images/finn_kijimi_coat.png" },
  { id: "finn_jacket_white_shirt", name: "Finn (Jacket - White Shirt)", category: "Hero", dlc: null, img: "Character images/finn_jacket_white_shirt.png" },
  { id: "garven_greis", name: "Garven Greis (Red Leader)", category: "Hero", dlc: null, img: "Character images/garven_greis.png" },
  { id: "general_leia_organa", name: "General Leia Organa", category: "Hero", dlc: null, img: "Character images/general_leia_organa.png" },
  { id: "general_leia_organa_bandaged", name: "General Leia Organa (Bandaged)", category: "Hero", dlc: null, img: "Character images/general_leia_organa_bandaged.png" },
  { id: "general_leia_organa_silver_robes", name: "General Leia Organa (Silver/Grey Robes)", category: "Hero", dlc: null, img: "Character images/general_leia_organa_silver_robes.png" },
  { id: "general_leia_organa_black_robes", name: "General Leia Organa (Black Robes)", category: "Hero", dlc: null, img: "Character images/general_leia_organa_black_robes.png" },
  { id: "general_leia_organa_ep9", name: "General Leia Organa (Episode IX)", category: "Hero", dlc: null, img: "Character images/general_leia_organa_ep9.png" },
  { id: "general_rieekan", name: "General Rieekan", category: "Hero", dlc: null, img: "Character images/general_rieekan.png" },
  { id: "general_rieekan_hoth_hood", name: "General Rieekan (Hoth - Hood)", category: "Hero", dlc: null, img: "Character images/general_rieekan_hoth_hood.png" },
  { id: "grakchawwaa", name: "Grakchawwaa", category: "Hero", dlc: null, img: "Character images/grakchawwaa.png" },
  { id: "gungan_warrior", name: "Gungan Warrior", category: "Hero", dlc: null, img: "Character images/gungan_warrior.png" },
  { id: "jannah", name: "Jannah", category: "Hero", dlc: null, img: "Character images/jannah.png" },
  { id: "jar_jar_binks", name: "Jar Jar Binks", category: "Hero", dlc: null, img: "Character images/jar_jar_binks.png" },
  { id: "jar_jar_senator", name: "Jar Jar (Senator)", category: "Hero", dlc: null, img: "Character images/jar_jar_senator.png" },
  { id: "jess_pava", name: "Jess Pava", category: "Hero", dlc: null, img: "Character images/jess_pava.png" },
  { id: "jet_porkins", name: "Jet Porkins", category: "Hero", dlc: null, img: "Character images/jet_porkins.png" },
  { id: "kaydel_connix", name: "Kaydel Connix", category: "Hero", dlc: null, img: "Character images/kaydel_connix.png" },
  { id: "kaydel_connix_ep9", name: "Kaydel Connix (Episode IX)", category: "Hero", dlc: null, img: "Character images/kaydel_connix_ep9.png" },
  { id: "leia_ep4", name: "Leia (Episode IV)", category: "Hero", dlc: null, img: "Character images/leia_ep4.png" },
  { id: "leia_jabbas_palace", name: "Leia (Jabba's Palace)", category: "Hero", dlc: null, img: "Character images/leia_jabbas_palace.png" },
  { id: "leia_cloud_city", name: "Leia (Cloud City)", category: "Hero", dlc: null, img: "Character images/leia_cloud_city.png" },
  { id: "leia_endor", name: "Leia (Endor)", category: "Hero", dlc: null, img: "Character images/leia_endor.png" },
  { id: "luke_skywalker_ep4", name: "Luke Skywalker (Episode IV)", category: "Hero", dlc: null, img: "Character images/luke_skywalker_ep4.png" },
  { id: "luke_skywalker_ceremony", name: "Luke Skywalker (Ceremony)", category: "Hero", dlc: null, img: "Character images/luke_skywalker_ceremony.png" },
  { id: "luke_skywalker_rebel_pilot", name: "Luke Skywalker (Rebel Pilot)", category: "Hero", dlc: null, img: "Character images/luke_skywalker_rebel_pilot.png" },
  { id: "mon_mothma", name: "Mon Mothma", category: "Hero", dlc: null, img: "Character images/mon_mothma.png" },
  { id: "nien_nunb", name: "Nien Nunb", category: "Hero", dlc: null, img: "Character images/nien_nunb.png" },
  { id: "padme_ship", name: "Padme (Ship)", category: "Hero", dlc: null, img: "Character images/padme_ship.png" },
  { id: "padme_clawed", name: "Padme (Clawed)", category: "Hero", dlc: null, img: "Character images/padme_clawed.png" },
  { id: "padme_handmaiden_orange", name: "Padme (Handmaiden - Orange)", category: "Hero", dlc: null, img: "Character images/padme_handmaiden_orange.png" },
  { id: "padme_battle_of_naboo", name: "Padme (Battle of Naboo)", category: "Hero", dlc: null, img: "Character images/padme_battle_of_naboo.png" },
  { id: "padme_pilot", name: "Padme (Pilot)", category: "Hero", dlc: null, img: "Character images/padme_pilot.png" },
  { id: "padme_pilot_helmet", name: "Padme (Pilot - Helmet)", category: "Hero", dlc: null, img: "Character images/padme_pilot_helmet.png" },
  { id: "padme_pregnant", name: "Padme (Pregnant)", category: "Hero", dlc: null, img: "Character images/padme_pregnant.png" },
  { id: "padme_silver_cape", name: "Padme (Silver Cape)", category: "Hero", dlc: null, img: "Character images/padme_silver_cape.png" },
  { id: "padme_tatooine_disguise", name: "Padme (Tatooine Disguise)", category: "Hero", dlc: null, img: "Character images/padme_tatooine_disguise.png" },
  { id: "poe_dameron_black_resistance_jacket", name: "Poe Dameron (Black Resistance Jacket)", category: "Hero", dlc: null, img: "Character images/poe_dameron_black_resistance_jacket.png" },
  { id: "poe_dameron_ep9", name: "Poe Dameron (Episode IX)", category: "Hero", dlc: null, img: "Character images/poe_dameron_ep9.png" },
  { id: "poe_dameron_jacket", name: "Poe Dameron (Jacket)", category: "Hero", dlc: null, img: "Character images/poe_dameron_jacket.png" },
  { id: "poe_dameron_kijimi_coat", name: "Poe Dameron (Kijimi Coat)", category: "Hero", dlc: null, img: "Character images/poe_dameron_kijimi_coat.png" },
  { id: "poe_dameron_pilot", name: "Poe Dameron (Pilot)", category: "Hero", dlc: null, img: "Character images/poe_dameron_pilot.png" },
  { id: "poe_dameron_pilot_helmet", name: "Poe Dameron (Pilot - Helmet)", category: "Hero", dlc: null, img: "Character images/poe_dameron_pilot_helmet.png" },
  { id: "rebel_friend", name: "Rebel Friend", category: "Hero", dlc: null, img: "Character images/rebel_friend.png" },
  { id: "ric_olie", name: "Ric Olie", category: "Hero", dlc: null, img: "Character images/ric_olie.png" },
  { id: "rose_tico", name: "Rose Tico", category: "Hero", dlc: null, img: "Character images/rose_tico.png" },
  { id: "rose_tico_crait", name: "Rose Tico (Crait)", category: "Hero", dlc: null, img: "Character images/rose_tico_crait.png" },
  { id: "rose_tico_ep9", name: "Rose Tico (Episode IX)", category: "Hero", dlc: null, img: "Character images/rose_tico_ep9.png" },
  { id: "tallie_lintra", name: "Tallie Lintra", category: "Hero", dlc: null, img: "Character images/tallie_lintra.png" },
  { id: "tarfful", name: "Tarfful", category: "Hero", dlc: null, img: "Character images/tarfful.png" },
  { id: "temmin_wexley", name: "Temmin Wexley", category: "Hero", dlc: null, img: "Character images/temmin_wexley.png" },
  { id: "theron_nett", name: "Theron Nett", category: "Hero", dlc: null, img: "Character images/theron_nett.png" },
  { id: "wedge_antilles", name: "Wedge Antilles", category: "Hero", dlc: null, img: "Character images/wedge_antilles.png" },
  { id: "wrobie_tyce", name: "Wrobie Tyce", category: "Hero", dlc: null, img: "Character images/wrobie_tyce.png" },
  { id: "zev_senesca", name: "Zev Senesca (Rogue 2)", category: "Hero", dlc: null, img: "Character images/zev_senesca.png" },

  // ─── SCAVENGERS (11) ────────────────────────────────────────────────────────
  { id: "chief_chirpa", name: "Chief Chirpa", category: "Scavenger", dlc: null, img: "Character images/chief_chirpa.png" },
  { id: "jawa", name: "Jawa", category: "Scavenger", dlc: null, img: "Character images/jawa.png" },
  { id: "logray", name: "Logray", category: "Scavenger", dlc: null, img: "Character images/logray.png" },
  { id: "paploo", name: "Paploo", category: "Scavenger", dlc: null, img: "Character images/paploo.png" },
  { id: "rey_ep7", name: "Rey (Episode VII)", category: "Scavenger", dlc: null, img: "Character images/rey_ep7.png" },
  { id: "rey_ep7_starkiller_base", name: "Rey (Episode VII - Starkiller Base)", category: "Scavenger", dlc: null, img: "Character images/rey_ep7_starkiller_base.png" },
  { id: "rey_scavenger_grey_vest", name: "Rey (Scavenger Grey Vest)", category: "Scavenger", dlc: null, img: "Character images/rey_scavenger_grey_vest.png" },
  { id: "teebo", name: "Teebo", category: "Scavenger", dlc: null, img: "Character images/teebo.png" },
  { id: "teedo", name: "Teedo", category: "Scavenger", dlc: null, img: "Character images/teedo.png" },
  { id: "tusken_raider", name: "Tusken Raider", category: "Scavenger", dlc: null, img: "Character images/tusken_raider.png" },
  { id: "wicket", name: "Wicket", category: "Scavenger", dlc: null, img: "Character images/wicket.png" },

  // ─── SCOUNDRELS (24) ────────────────────────────────────────────────────────
  { id: "bala_tik", name: "Bala-Tik", category: "Scoundrel", dlc: null, img: "Character images/bala_tik.png" },
  { id: "chewbacca", name: "Chewbacca", category: "Scoundrel", dlc: null, img: "Character images/chewbacca.png" },
  { id: "dj", name: "DJ", category: "Scoundrel", dlc: null, img: "Character images/dj.png" },
  { id: "doctor_evazan", name: "Doctor Evazan", category: "Scoundrel", dlc: null, img: "Character images/doctor_evazan.png" },
  { id: "han_solo_ep4", name: "Han Solo (Episode IV)", category: "Scoundrel", dlc: null, img: "Character images/han_solo_ep4.png" },
  { id: "han_solo_ep5", name: "Han Solo (Episode V)", category: "Scoundrel", dlc: null, img: "Character images/han_solo_ep5.png" },
  { id: "han_solo_endor", name: "Han Solo (Endor)", category: "Scoundrel", dlc: null, img: "Character images/han_solo_endor.png" },
  { id: "han_solo_hoth", name: "Han Solo (Hoth)", category: "Scoundrel", dlc: null, img: "Character images/han_solo_hoth.png" },
  { id: "han_solo_hoth_hood", name: "Han Solo (Hoth - Hood)", category: "Scoundrel", dlc: null, img: "Character images/han_solo_hoth_hood.png" },
  { id: "han_solo_carbonite_shirt", name: "Han Solo (Carbonite - Shirt)", category: "Scoundrel", dlc: null, img: "Character images/han_solo_carbonite_shirt.png" },
  { id: "han_solo_ep7", name: "Han Solo (Episode VII)", category: "Scoundrel", dlc: null, img: "Character images/han_solo_ep7.png" },
  { id: "lando_calrissian_ep9", name: "Lando Calrissian (Episode IX)", category: "Scoundrel", dlc: null, img: "Character images/lando_calrissian_ep9.png" },
  { id: "lando_calrissian_hermit", name: "Lando Calrissian (Hermit)", category: "Scoundrel", dlc: null, img: "Character images/lando_calrissian_hermit.png" },
  { id: "lando_calrissian_ep5", name: "Lando Calrissian (Episode V)", category: "Scoundrel", dlc: null, img: "Character images/lando_calrissian_ep5.png" },
  { id: "lando_calrissian_ep6_general", name: "Lando Calrissian (Episode VI - General)", category: "Scoundrel", dlc: null, img: "Character images/lando_calrissian_ep6_general.png" },
  { id: "lando_calrissian_han_solos_clothes", name: "Lando Calrissian (Han Solo's Clothes)", category: "Scoundrel", dlc: null, img: "Character images/lando_calrissian_han_solos_clothes.png" },
  { id: "lando_calrissian_jabbas_palace", name: "Lando Calrissian (Jabba's Palace)", category: "Scoundrel", dlc: null, img: "Character images/lando_calrissian_jabbas_palace.png" },
  { id: "maz_kanata", name: "Maz Kanata", category: "Scoundrel", dlc: null, img: "Character images/maz_kanata.png" },
  { id: "ponda_baba", name: "Ponda Baba", category: "Scoundrel", dlc: null, img: "Character images/ponda_baba.png" },
  { id: "sidon_ithano", name: "Sidon Ithano", category: "Scoundrel", dlc: null, img: "Character images/sidon_ithano.png" },
  { id: "tasu_leech", name: "Tasu Leech", category: "Scoundrel", dlc: null, img: "Character images/tasu_leech.png" },
  { id: "wandering_wookiee", name: "Wandering Wookiee", category: "Scoundrel", dlc: null, img: "Character images/wandering_wookiee.png" },
  { id: "zorii_bliss", name: "Zorii Bliss", category: "Scoundrel", dlc: null, img: "Character images/zorii_bliss.png" },

  // ─── BOUNTY HUNTERS (16) ────────────────────────────────────────────────────
  { id: "4_lom", name: "4-LOM", category: "Bounty Hunter", dlc: null, img: "Character images/4_lom.png" },
  { id: "aurra_sing", name: "Aurra Sing", category: "Bounty Hunter", dlc: null, img: "Character images/aurra_sing.png" },
  { id: "bazine_netal", name: "Bazine Netal", category: "Bounty Hunter", dlc: null, img: "Character images/bazine_netal.png" },
  { id: "boba_fett", name: "Boba Fett", category: "Bounty Hunter", dlc: null, img: "Character images/boba_fett.png" },
  { id: "bossk", name: "Bossk", category: "Bounty Hunter", dlc: null, img: "Character images/bossk.png" },
  { id: "carib_diss", name: "Carib Diss", category: "Bounty Hunter", dlc: null, img: "Character images/carib_diss.png" },
  { id: "dengar", name: "Dengar", category: "Bounty Hunter", dlc: null, img: "Character images/dengar.png" },
  { id: "greedo", name: "Greedo", category: "Bounty Hunter", dlc: null, img: "Character images/greedo.png" },
  { id: "ig_88", name: "IG-88", category: "Bounty Hunter", dlc: null, img: "Character images/ig_88.png" },
  { id: "jango_fett", name: "Jango Fett", category: "Bounty Hunter", dlc: null, img: "Character images/jango_fett.png" },
  { id: "jango_fett_casual", name: "Jango Fett (Casual)", category: "Bounty Hunter", dlc: null, img: "Character images/jango_fett_casual.png" },
  { id: "leia_boussh_disguise", name: "Leia (Boussh Disguise)", category: "Bounty Hunter", dlc: null, img: "Character images/leia_boussh_disguise.png" },
  { id: "rothgar_deng", name: "Rothgar Deng", category: "Bounty Hunter", dlc: null, img: "Character images/rothgar_deng.png" },
  { id: "zam_wesell_human", name: "Zam Wesell (Human)", category: "Bounty Hunter", dlc: null, img: "Character images/zam_wesell_human.png" },
  { id: "zam_wesell_alien", name: "Zam Wesell (Alien Face)", category: "Bounty Hunter", dlc: null, img: "Character images/zam_wesell_alien.png" },
  { id: "zuckuss", name: "Zuckuss", category: "Bounty Hunter", dlc: null, img: "Character images/zuckuss.png" },

  // ─── VILLAINS (65) ──────────────────────────────────────────────────────────
  { id: "ap_lek", name: "Ap'lek", category: "Villain", dlc: null, img: "Character images/ap_lek.png" },
  { id: "b1_battle_droid", name: "B1 Battle Droid", category: "Villain", dlc: null, img: "Character images/b1_battle_droid.png" },
  { id: "b1_battle_droid_commander", name: "B1 Battle Droid (Commander)", category: "Villain", dlc: null, img: "Character images/b1_battle_droid_commander.png" },
  { id: "b1_battle_droid_geonosis", name: "B1 Battle Droid (Geonosis)", category: "Villain", dlc: null, img: "Character images/b1_battle_droid_geonosis.png" },
  { id: "b1_battle_droid_heavy_assault", name: "B1 Battle Droid (Heavy Assault)", category: "Villain", dlc: null, img: "Character images/b1_battle_droid_heavy_assault.png" },
  { id: "b1_battle_droid_kashyyyk", name: "B1 Battle Droid (Kashyyyk)", category: "Villain", dlc: null, img: "Character images/b1_battle_droid_kashyyyk.png" },
  { id: "b1_battle_droid_security", name: "B1 Battle Droid (Security)", category: "Villain", dlc: null, img: "Character images/b1_battle_droid_security.png" },
  { id: "captain_canady", name: "Captain Canady", category: "Villain", dlc: null, img: "Character images/captain_canady.png" },
  { id: "captain_peavey", name: "Captain Peavey", category: "Villain", dlc: null, img: "Character images/captain_peavey.png" },
  { id: "captain_phasma", name: "Captain Phasma", category: "Villain", dlc: null, img: "Character images/captain_phasma.png" },
  { id: "captain_phasma_cracked_helmet", name: "Captain Phasma (Cracked Helmet)", category: "Villain", dlc: null, img: "Character images/captain_phasma_cracked_helmet.png" },
  { id: "cardo", name: "Cardo", category: "Villain", dlc: null, img: "Character images/cardo.png" },
  { id: "commander_jir", name: "Commander Jir", category: "Villain", dlc: null, img: "Character images/commander_jir.png" },
  { id: "dj_first_order", name: "DJ (First Order)", category: "Villain", dlc: null, img: "Character images/dj_first_order.png" },
  { id: "emperors_royal_guard", name: "Emperor's Royal Guard", category: "Villain", dlc: null, img: "Character images/emperors_royal_guard.png" },
  { id: "empire_captain", name: "Empire Captain", category: "Villain", dlc: null, img: "Character images/empire_captain.png" },
  { id: "fn_2199", name: "FN-2199", category: "Villain", dlc: null, img: "Character images/fn_2199.png" },
  { id: "finn_fn2187_no_helmet", name: "Finn (FN-2187 - No Helmet)", category: "Villain", dlc: null, img: "Character images/finn_fn2187_no_helmet.png" },
  { id: "finn_fn2187", name: "Finn (FN-2187)", category: "Villain", dlc: null, img: "Character images/finn_fn2187.png" },
  { id: "finn_first_order", name: "Finn (First Order)", category: "Villain", dlc: null, img: "Character images/finn_first_order.png" },
  { id: "finn_ep8_supremacy", name: "Finn (Episode VIII - Supremacy)", category: "Villain", dlc: null, img: "Character images/finn_ep8_supremacy.png" },
  { id: "first_order_flametrooper", name: "First Order Flametrooper", category: "Villain", dlc: null, img: "Character images/first_order_flametrooper.png" },
  { id: "first_order_jet_trooper", name: "First Order Jet Trooper", category: "Villain", dlc: null, img: "Character images/first_order_jet_trooper.png" },
  { id: "first_order_officer", name: "First Order Officer", category: "Villain", dlc: null, img: "Character images/first_order_officer.png" },
  { id: "first_order_officer_kijimi", name: "First Order Officer (Kijimi)", category: "Villain", dlc: null, img: "Character images/first_order_officer_kijimi.png" },
  { id: "first_order_snowtrooper", name: "First Order Snowtrooper", category: "Villain", dlc: null, img: "Character images/first_order_snowtrooper.png" },
  { id: "first_order_cold_weather_assault_trooper", name: "First Order Cold Weather Assault Trooper", category: "Villain", dlc: null, img: "Character images/first_order_cold_weather_assault_trooper.png" },
  { id: "first_order_special_forces_fighter_pilot", name: "First Order Special Forces Fighter Pilot", category: "Villain", dlc: null, img: "Character images/first_order_special_forces_fighter_pilot.png" },
  { id: "first_order_tie_fighter_pilot", name: "First Order TIE Fighter Pilot", category: "Villain", dlc: null, img: "Character images/first_order_tie_fighter_pilot.png" },
  { id: "general_grievous", name: "General Grievous", category: "Villain", dlc: null, img: "Character images/general_grievous.png" },
  { id: "general_hux", name: "General Hux", category: "Villain", dlc: null, img: "Character images/general_hux.png" },
  { id: "han_solo_stormtrooper", name: "Han Solo (Stormtrooper)", category: "Villain", dlc: null, img: "Character images/han_solo_stormtrooper.png" },
  { id: "han_solo_stormtrooper_no_helmet", name: "Han Solo (Stormtrooper - No Helmet)", category: "Villain", dlc: null, img: "Character images/han_solo_stormtrooper_no_helmet.png" },
  { id: "imperial_fleet_trooper", name: "Imperial Fleet Trooper", category: "Villain", dlc: null, img: "Character images/imperial_fleet_trooper.png" },
  { id: "imperial_gunnery_technician", name: "Imperial Gunnery Technician", category: "Villain", dlc: null, img: "Character images/imperial_gunnery_technician.png" },
  { id: "kuruk", name: "Kuruk", category: "Villain", dlc: null, img: "Character images/kuruk.png" },
  { id: "luke_skywalker_stormtrooper", name: "Luke Skywalker (Stormtrooper)", category: "Villain", dlc: null, img: "Character images/luke_skywalker_stormtrooper.png" },
  { id: "luke_skywalker_stormtrooper_no_helmet", name: "Luke Skywalker (Stormtrooper - No Helmet)", category: "Villain", dlc: null, img: "Character images/luke_skywalker_stormtrooper_no_helmet.png" },
  { id: "00m_9", name: "00M-9", category: "Villain", dlc: null, img: "Character images/00m_9.png" },
  { id: "pryde", name: "Pryde", category: "Villain", dlc: null, img: "Character images/pryde.png" },
  { id: "rose_tico_first_order", name: "Rose Tico (First Order)", category: "Villain", dlc: null, img: "Character images/rose_tico_first_order.png" },
  { id: "rose_tico_ep8_supremacy", name: "Rose Tico (Episode VIII - Supremacy)", category: "Villain", dlc: null, img: "Character images/rose_tico_ep8_supremacy.png" },
  { id: "sandtrooper", name: "Sandtrooper", category: "Villain", dlc: null, img: "Character images/sandtrooper.png" },
  { id: "sandtrooper_commander", name: "Sandtrooper (Commander)", category: "Villain", dlc: null, img: "Character images/sandtrooper_commander.png" },
  { id: "sandtrooper_sergeant", name: "Sandtrooper (Sergeant)", category: "Villain", dlc: null, img: "Character images/sandtrooper_sergeant.png" },
  { id: "scout_trooper", name: "Scout Trooper", category: "Villain", dlc: null, img: "Character images/scout_trooper.png" },
  { id: "scout_trooper_kashyyyk", name: "Scout Trooper (Kashyyyk)", category: "Villain", dlc: null, img: "Character images/scout_trooper_kashyyyk.png" },
  { id: "sith_jet_trooper", name: "Sith Jet Trooper", category: "Villain", dlc: null, img: "Character images/sith_jet_trooper.png" },
  { id: "sith_trooper", name: "Sith Trooper", category: "Villain", dlc: null, img: "Character images/sith_trooper.png" },
  { id: "snowtrooper", name: "Snowtrooper", category: "Villain", dlc: null, img: "Character images/snowtrooper.png" },
  { id: "sovereign_protector", name: "Sovereign Protector", category: "Villain", dlc: null, img: "Character images/sovereign_protector.png" },
  { id: "stormtrooper_empire_sergeant", name: "Stormtrooper (Empire Sergeant)", category: "Villain", dlc: null, img: "Character images/stormtrooper_empire_sergeant.png" },
  { id: "stormtrooper", name: "Stormtrooper", category: "Villain", dlc: null, img: "Character images/stormtrooper.png" },
  { id: "stormtrooper_empire_commander", name: "Stormtrooper (Empire Commander)", category: "Villain", dlc: null, img: "Character images/stormtrooper_empire_commander.png" },
  { id: "stormtrooper_first_order_driver", name: "Stormtrooper (First Order - Driver)", category: "Villain", dlc: null, img: "Character images/stormtrooper_first_order_driver.png" },
  { id: "stormtrooper_first_order_sergeant", name: "Stormtrooper (First Order Sergeant)", category: "Villain", dlc: null, img: "Character images/stormtrooper_first_order_sergeant.png" },
  { id: "stormtrooper_first_order_officer", name: "Stormtrooper (First Order Officer)", category: "Villain", dlc: null, img: "Character images/stormtrooper_first_order_officer.png" },
  { id: "stormtrooper_first_order_heavy_assault", name: "Stormtrooper (First Order Heavy Assault)", category: "Villain", dlc: null, img: "Character images/stormtrooper_first_order_heavy_assault.png" },
  { id: "stormtrooper_first_order_squad_leader", name: "Stormtrooper (First Order Squad Leader)", category: "Villain", dlc: null, img: "Character images/stormtrooper_first_order_squad_leader.png" },
  { id: "stormtrooper_first_order", name: "Stormtrooper (First Order)", category: "Villain", dlc: null, img: "Character images/stormtrooper_first_order.png" },
  { id: "tie_fighter_pilot", name: "TIE Fighter Pilot", category: "Villain", dlc: null, img: "Character images/tie_fighter_pilot.png" },
  { id: "tarkin", name: "Tarkin", category: "Villain", dlc: null, img: "Character images/tarkin.png" },
  { id: "trudgen", name: "Trudgen", category: "Villain", dlc: null, img: "Character images/trudgen.png" },
  { id: "ushar", name: "Ushar", category: "Villain", dlc: null, img: "Character images/ushar.png" },
  { id: "vicrul", name: "Vicrul", category: "Villain", dlc: null, img: "Character images/vicrul.png" },

  // ─── DARK SIDE (19) ─────────────────────────────────────────────────────────
  { id: "anakin_skywalker_charred", name: "Anakin Skywalker (Charred)", category: "Dark Side", dlc: null, img: "Character images/anakin_skywalker_charred.png" },
  { id: "anakin_skywalker_yellow_eyes", name: "Anakin Skywalker (Yellow Eyes)", category: "Dark Side", dlc: null, img: "Character images/anakin_skywalker_yellow_eyes.png" },
  { id: "count_dooku", name: "Count Dooku", category: "Dark Side", dlc: null, img: "Character images/count_dooku.png" },
  { id: "darth_maul_no_cape", name: "Darth Maul (No Cape)", category: "Dark Side", dlc: null, img: "Character images/darth_maul_no_cape.png" },
  { id: "darth_maul", name: "Darth Maul", category: "Dark Side", dlc: null, img: "Character images/darth_maul.png" },
  { id: "darth_vader", name: "Darth Vader", category: "Dark Side", dlc: null, img: "Character images/darth_vader.png" },
  { id: "darth_vader_no_helmet", name: "Darth Vader (No Helmet)", category: "Dark Side", dlc: null, img: "Character images/darth_vader_no_helmet.png" },
  { id: "kylo_ren_ep9", name: "Kylo Ren (Episode IX)", category: "Dark Side", dlc: null, img: "Character images/kylo_ren_ep9.png" },
  { id: "kylo_ren_no_helmet", name: "Kylo Ren (No Helmet)", category: "Dark Side", dlc: null, img: "Character images/kylo_ren_no_helmet.png" },
  { id: "kylo_ren_no_helmet_scar", name: "Kylo Ren (No Helmet - Scar)", category: "Dark Side", dlc: null, img: "Character images/kylo_ren_no_helmet_scar.png" },
  { id: "kylo_ren_topless", name: "Kylo Ren (Topless)", category: "Dark Side", dlc: null, img: "Character images/kylo_ren_topless.png" },
  { id: "kylo_ren", name: "Kylo Ren", category: "Dark Side", dlc: null, img: "Character images/kylo_ren.png" },
  { id: "palpatine_scarred", name: "Palpatine (Scarred)", category: "Dark Side", dlc: null, img: "Character images/palpatine_scarred.png" },
  { id: "palpatine_senator", name: "Palpatine (Senator)", category: "Dark Side", dlc: null, img: "Character images/palpatine_senator.png" },
  { id: "palpatine_chancellor_grey", name: "Palpatine (Chancellor - Grey)", category: "Dark Side", dlc: null, img: "Character images/palpatine_chancellor_grey.png" },
  { id: "palpatine_chancellor_red", name: "Palpatine (Chancellor - Red)", category: "Dark Side", dlc: null, img: "Character images/palpatine_chancellor_red.png" },
  { id: "rey_sith", name: "Rey (Sith)", category: "Dark Side", dlc: null, img: "Character images/rey_sith.png" },
  { id: "snoke", name: "Snoke", category: "Dark Side", dlc: null, img: "Character images/snoke.png" },
  { id: "the_emperor", name: "The Emperor", category: "Dark Side", dlc: null, img: "Character images/the_emperor.png" },

  // ─── ASTROMECH DROIDS (19) ──────────────────────────────────────────────────
  { id: "bb_8", name: "BB-8", category: "Astromech Droid", dlc: null, img: "Character images/bb_8.png" },
  { id: "bb_8_disguise", name: "BB-8 (Disguise)", category: "Astromech Droid", dlc: null, img: "Character images/bb_8_disguise.png" },
  { id: "bb_9e", name: "BB-9E", category: "Astromech Droid", dlc: null, img: "Character images/bb_9e.png" },
  { id: "g8_r3", name: "G8-R3", category: "Astromech Droid", dlc: null, img: "Character images/g8_r3.png" },
  { id: "k3_r1", name: "K3-R1", category: "Astromech Droid", dlc: null, img: "Character images/k3_r1.png" },
  { id: "r2_a6", name: "R2-A6", category: "Astromech Droid", dlc: null, img: "Character images/r2_a6.png" },
  { id: "r2_b1", name: "R2-B1", category: "Astromech Droid", dlc: null, img: "Character images/r2_b1.png" },
  { id: "r2_d2", name: "R2-D2", category: "Astromech Droid", dlc: null, img: "Character images/r2_d2.png" },
  { id: "r2_d2_swamp", name: "R2-D2 (Swamp)", category: "Astromech Droid", dlc: null, img: "Character images/r2_d2_swamp.png" },
  { id: "r2_d2_waiter", name: "R2-D2 (Waiter)", category: "Astromech Droid", dlc: null, img: "Character images/r2_d2_waiter.png" },
  { id: "r2_kt", name: "R2-KT", category: "Astromech Droid", dlc: null, img: "Character images/r2_kt.png" },
  { id: "r2_n3", name: "R2-N3", category: "Astromech Droid", dlc: null, img: "Character images/r2_n3.png" },
  { id: "r2_q5", name: "R2-Q5", category: "Astromech Droid", dlc: null, img: "Character images/r2_q5.png" },
  { id: "r2_r9", name: "R2-R9", category: "Astromech Droid", dlc: null, img: "Character images/r2_r9.png" },
  { id: "r4_m9", name: "R4-M9", category: "Astromech Droid", dlc: null, img: "Character images/r4_m9.png" },
  { id: "r4_p17", name: "R4-P17", category: "Astromech Droid", dlc: null, img: "Character images/r4_p17.png" },
  { id: "r5_2je", name: "R5-2JE", category: "Astromech Droid", dlc: null, img: "Character images/r5_2je.png" },
  { id: "r5_d4", name: "R5-D4", category: "Astromech Droid", dlc: null, img: "Character images/r5_d4.png" },
  { id: "r5_m2", name: "R5-M2", category: "Astromech Droid", dlc: null, img: "Character images/r5_m2.png" },

  // ─── PROTOCOL DROIDS (13) ───────────────────────────────────────────────────
  { id: "c_3po", name: "C-3PO", category: "Protocol Droid", dlc: null, img: "Character images/c_3po.png" },
  { id: "c_3po_kijimi_coat", name: "C-3PO (Kijimi Coat)", category: "Protocol Droid", dlc: null, img: "Character images/c_3po_kijimi_coat.png" },
  { id: "c_3po_ep1", name: "C-3PO (Episode I)", category: "Protocol Droid", dlc: null, img: "Character images/c_3po_ep1.png" },
  { id: "c_3po_red_arm", name: "C-3PO (Red Arm)", category: "Protocol Droid", dlc: null, img: "Character images/c_3po_red_arm.png" },
  { id: "c_3po_red_eyes", name: "C-3PO (Red Eyes)", category: "Protocol Droid", dlc: null, img: "Character images/c_3po_red_eyes.png" },
  { id: "c_3po_rusted", name: "C-3PO (Rusted)", category: "Protocol Droid", dlc: null, img: "Character images/c_3po_rusted.png" },
  { id: "e_3po", name: "E-3P0", category: "Protocol Droid", dlc: null, img: "Character images/e_3po.png" },
  { id: "h1_nt", name: "H1-NT", category: "Protocol Droid", dlc: null, img: "Character images/h1_nt.png" },
  { id: "k_3po", name: "K-3PO", category: "Protocol Droid", dlc: null, img: "Character images/k_3po.png" },
  { id: "me_8d9", name: "ME-8D9", category: "Protocol Droid", dlc: null, img: "Character images/me_8d9.png" },
  { id: "r_3po", name: "R-3P0", category: "Protocol Droid", dlc: null, img: "Character images/r_3po.png" },
  { id: "ra_7", name: "RA-7", category: "Protocol Droid", dlc: null, img: "Character images/ra_7.png" },
  { id: "tc_14", name: "TC-14", category: "Protocol Droid", dlc: null, img: "Character images/tc_14.png" },

  // ─── EXTRAS (79) ────────────────────────────────────────────────────────────
  { id: "2_1b", name: "2-1B", category: "Extra", dlc: null, img: "Character images/2_1b.png" },
  { id: "8d8", name: "8D8", category: "Extra", dlc: null, img: "Character images/8d8.png" },
  { id: "ad_4m", name: "AD-4M", category: "Extra", dlc: null, img: "Character images/ad_4m.png" },
  { id: "alcida_auka", name: "Alcida-Auka", category: "Extra", dlc: null, img: "Character images/alcida_auka.png" },
  { id: "anakin_skywalker_ep1", name: "Anakin Skywalker (Episode I)", category: "Extra", dlc: null, img: "Character images/anakin_skywalker_ep1.png" },
  { id: "anakin_skywalker_podracer", name: "Anakin Skywalker (Podracer)", category: "Extra", dlc: null, img: "Character images/anakin_skywalker_podracer.png" },
  { id: "anakin_skywalker_pilot", name: "Anakin Skywalker (Pilot)", category: "Extra", dlc: null, img: "Character images/anakin_skywalker_pilot.png" },
  { id: "b2_super_battle_droid", name: "B2 Super Battle Droid", category: "Extra", dlc: null, img: "Character images/b2_super_battle_droid.png" },
  { id: "babu_frik", name: "Babu Frik", category: "Extra", dlc: null, img: "Character images/babu_frik.png" },
  { id: "bib_fortuna", name: "Bib Fortuna", category: "Extra", dlc: null, img: "Character images/bib_fortuna.png" },
  { id: "boba_fett_young", name: "Boba Fett (Young)", category: "Extra", dlc: null, img: "Character images/boba_fett_young.png" },
  { id: "bobbajo", name: "Bobbajo", category: "Extra", dlc: null, img: "Character images/bobbajo.png" },
  { id: "d_0", name: "D-0", category: "Extra", dlc: null, img: "Character images/d_0.png" },
  { id: "dellso_prin", name: "Dellso Prin", category: "Extra", dlc: null, img: "Character images/dellso_prin.png" },
  { id: "dexter_jettster", name: "Dexter Jettster", category: "Extra", dlc: null, img: "Character images/dexter_jettster.png" },
  { id: "droideka", name: "Droideka", category: "Extra", dlc: null, img: "Character images/droideka.png" },
  { id: "ev_9d9", name: "EV-9D9 Supervisor Droid", category: "Extra", dlc: null, img: "Character images/ev_9d9.png" },
  { id: "figrin_dan", name: "Figrin D'an", category: "Extra", dlc: null, img: "Character images/figrin_dan.png" },
  { id: "fode_and_beed", name: "Fode and Beed", category: "Extra", dlc: null, img: "Character images/fode_and_beed.png" },
  { id: "gasgano", name: "Gasgano", category: "Extra", dlc: null, img: "Character images/gasgano.png" },
  { id: "gonk_droid", name: "Gonk Droid", category: "Extra", dlc: null, img: "Character images/gonk_droid.png" },
  { id: "gonkatine", name: "Gonkatine", category: "Extra", dlc: null, img: "Character images/gonkatine.png" },
  { id: "grebe_korora", name: "Grebe-Korora", category: "Extra", dlc: null, img: "Character images/grebe_korora.png" },
  { id: "greeata_jendowanian", name: "Greeata Jendowanian", category: "Extra", dlc: null, img: "Character images/greeata_jendowanian.png" },
  { id: "grummgar", name: "Grummgar", category: "Extra", dlc: null, img: "Character images/grummgar.png" },
  { id: "han_solo_carbonite", name: "Han Solo (Carbonite)", category: "Extra", dlc: null, img: "Character images/han_solo_carbonite.png" },
  { id: "ig_101_magna_guard", name: "IG-101 Magna Guard Droid", category: "Extra", dlc: null, img: "Character images/ig_101_magna_guard.png" },
  { id: "imperial_probe_droid", name: "Imperial Probe Droid", category: "Extra", dlc: null, img: "Character images/imperial_probe_droid.png" },
  { id: "jabba_the_hutt", name: "Jabba the Hutt", category: "Extra", dlc: null, img: "Character images/jabba_the_hutt.png" },
  { id: "jango_fett_clone", name: "Jango Fett (Clone)", category: "Extra", dlc: null, img: "Character images/jango_fett_clone.png" },
  { id: "jubnuk", name: "Jubnuk", category: "Extra", dlc: null, img: "Character images/jubnuk.png" },
  { id: "klaud", name: "Klaud", category: "Extra", dlc: null, img: "Character images/klaud.png" },
  { id: "lc_24", name: "LC-24", category: "Extra", dlc: null, img: "Character images/lc_24.png" },
  { id: "lama_su", name: "Lama Su", category: "Extra", dlc: null, img: "Character images/lama_su.png" },
  { id: "lobot", name: "Lobot", category: "Extra", dlc: null, img: "Character images/lobot.png" },
  { id: "luke_skywalker_old_ahch_to", name: "Luke Skywalker (Old - Ahch To)", category: "Extra", dlc: null, img: "Character images/luke_skywalker_old_ahch_to.png" },
  { id: "luke_skywalker_old_raincoat", name: "Luke Skywalker (Old - Raincoat)", category: "Extra", dlc: null, img: "Character images/luke_skywalker_old_raincoat.png" },
  { id: "malakili", name: "Malakili", category: "Extra", dlc: null, img: "Character images/malakili.png" },
  { id: "mama_the_hutt", name: "Mama the Hutt", category: "Extra", dlc: null, img: "Character images/mama_the_hutt.png" },
  { id: "mas_amedda", name: "Mas Amedda", category: "Extra", dlc: null, img: "Character images/mas_amedda.png" },
  { id: "master_codebreaker", name: "Master Codebreaker", category: "Extra", dlc: null, img: "Character images/master_codebreaker.png" },
  { id: "mawhonic", name: "Mawhonic", category: "Extra", dlc: null, img: "Character images/mawhonic.png" },
  { id: "max_rebo", name: "Max Rebo", category: "Extra", dlc: null, img: "Character images/max_rebo.png" },
  { id: "mister_bones", name: "Mister Bones", category: "Extra", dlc: null, img: "Character images/mister_bones.png" },
  { id: "mouse_droid", name: "Mouse Droid", category: "Extra", dlc: null, img: "Character images/mouse_droid.png" },
  { id: "mustafarian", name: "Mustafarian", category: "Extra", dlc: null, img: "Character images/mustafarian.png" },
  { id: "nambi_ghima", name: "Nambi Ghima", category: "Extra", dlc: null, img: "Character images/nambi_ghima.png" },
  { id: "nute_gunray", name: "Nute Gunray", category: "Extra", dlc: null, img: "Character images/nute_gunray.png" },
  { id: "ody_mandrell", name: "Ody Mandrell", category: "Extra", dlc: null, img: "Character images/ody_mandrell.png" },
  { id: "oola", name: "Oola", category: "Extra", dlc: null, img: "Character images/oola.png" },
  { id: "pit_droid", name: "Pit Droid", category: "Extra", dlc: null, img: "Character images/pit_droid.png" },
  { id: "poggle_the_lesser", name: "Poggle the Lesser", category: "Extra", dlc: null, img: "Character images/poggle_the_lesser.png" },
  { id: "praetorian_guard_first", name: "Praetorian Guard (First Guard)", category: "Extra", dlc: null, img: "Character images/praetorian_guard_first.png" },
  { id: "praetorian_guard_seventh", name: "Praetorian Guard (Seventh Guard)", category: "Extra", dlc: null, img: "Character images/praetorian_guard_seventh.png" },
  { id: "praetorian_guard_third", name: "Praetorian Guard (Third Guard)", category: "Extra", dlc: null, img: "Character images/praetorian_guard_third.png" },
  { id: "praetorian_guard_eighth", name: "Praetorian Guard (Eighth Guard)", category: "Extra", dlc: null, img: "Character images/praetorian_guard_eighth.png" },
  { id: "queen_amidala", name: "Queen Amidala", category: "Extra", dlc: null, img: "Character images/queen_amidala.png" },
  { id: "rancor", name: "Rancor", category: "Extra", dlc: null, img: "Character images/rancor.png" },
  { id: "ratts_tyerell", name: "Ratts Tyerell", category: "Extra", dlc: null, img: "Character images/ratts_tyerell.png" },
  { id: "ree_yees", name: "Ree-Yees", category: "Extra", dlc: null, img: "Character images/ree_yees.png" },
  { id: "roger", name: "Roger", category: "Extra", dlc: null, img: "Character images/roger.png" },
  { id: "rune_haako", name: "Rune Haako", category: "Extra", dlc: null, img: "Character images/rune_haako.png" },
  { id: "salacious_crumb", name: "Salacious Crumb", category: "Extra", dlc: null, img: "Character images/salacious_crumb.png" },
  { id: "sebulba", name: "Sebulba", category: "Extra", dlc: null, img: "Character images/sebulba.png" },
  { id: "senate_guard", name: "Senate Guard", category: "Extra", dlc: null, img: "Character images/senate_guard.png" },
  { id: "shmi", name: "Shmi", category: "Extra", dlc: null, img: "Character images/shmi.png" },
  { id: "sith_acolyte", name: "Sith Acolyte", category: "Extra", dlc: null, img: "Character images/sith_acolyte.png" },
  { id: "sith_probe_droid", name: "Sith Probe Droid", category: "Extra", dlc: null, img: "Character images/sith_probe_droid.png" },
  { id: "sy_snootles", name: "Sy Snootles", category: "Extra", dlc: null, img: "Character images/sy_snootles.png" },
  { id: "temiri_blagg", name: "Temiri Blagg", category: "Extra", dlc: null, img: "Character images/temiri_blagg.png" },
  { id: "tion_medon", name: "Tion Medon", category: "Extra", dlc: null, img: "Character images/tion_medon.png" },
  { id: "ubbla_mollbro", name: "Ubbla Mollbro", category: "Extra", dlc: null, img: "Character images/ubbla_mollbro.png" },
  { id: "ugnaught", name: "Ugnaught", category: "Extra", dlc: null, img: "Character images/ugnaught.png" },
  { id: "unkar_plutt", name: "Unkar Plutt", category: "Extra", dlc: null, img: "Character images/unkar_plutt.png" },
  { id: "wampa", name: "Wampa", category: "Extra", dlc: null, img: "Character images/wampa.png" },
  { id: "watto", name: "Watto", category: "Extra", dlc: null, img: "Character images/watto.png" },
  { id: "weequay", name: "Weequay", category: "Extra", dlc: null, img: "Character images/weequay.png" },
  { id: "willrow_hood", name: "Willrow Hood", category: "Extra", dlc: null, img: "Character images/willrow_hood.png" },

  // ═══════════════════════════════════════════════════════════════════════════
  // DLC PACKS
  // ═══════════════════════════════════════════════════════════════════════════

  // ─── CLASSIC CHARACTERS PACK ────────────────────────────────────────────────
  { id: "dlc_luke_skywalker_classic", name: "Luke Skywalker (Classic)", category: "Jedi", dlc: "Classic Characters Pack", img: "Character images/dlc_luke_skywalker_classic.png" },
  { id: "dlc_princess_leia_classic", name: "Princess Leia (Classic)", category: "Hero", dlc: "Classic Characters Pack", img: "Character images/dlc_princess_leia_classic.png" },
  { id: "dlc_han_solo_classic", name: "Han Solo (Classic)", category: "Scoundrel", dlc: "Classic Characters Pack", img: "Character images/dlc_han_solo_classic.png" },
  { id: "dlc_darth_vader_classic", name: "Darth Vader (Classic)", category: "Dark Side", dlc: "Classic Characters Pack", img: "Character images/dlc_darth_vader_classic.png" },
  { id: "dlc_lando_calrissian_classic", name: "Lando Calrissian (Classic)", category: "Scoundrel", dlc: "Classic Characters Pack", img: "Character images/dlc_lando_calrissian_classic.png" },

  // ─── TROOPER PACK ───────────────────────────────────────────────────────────
  { id: "dlc_death_trooper", name: "Death Trooper", category: "Villain", dlc: "Trooper Pack", img: "Character images/dlc_death_trooper.png" },
  { id: "dlc_incinerator_trooper", name: "Incinerator Trooper", category: "Villain", dlc: "Trooper Pack", img: "Character images/dlc_incinerator_trooper.png" },
  { id: "dlc_range_trooper", name: "Range Trooper", category: "Villain", dlc: "Trooper Pack", img: "Character images/dlc_range_trooper.png" },
  { id: "dlc_imperial_shore_trooper", name: "Imperial Shore Trooper", category: "Villain", dlc: "Trooper Pack", img: "Character images/dlc_imperial_shore_trooper.png" },
  { id: "dlc_mimban_stormtrooper", name: "Mimban Stormtrooper", category: "Villain", dlc: "Trooper Pack", img: "Character images/dlc_mimban_stormtrooper.png" },

  // ─── VILLAINS PACK ──────────────────────────────────────────────────────────
  // Note: The in-game "Villains Pack" is the Solo: A Star Wars Story Pack
  // which contains these villain-aligned characters from that film.
  { id: "dlc_han_solo_young", name: "Han Solo (Young)", category: "Scoundrel", dlc: "Villains Pack", img: "Character images/dlc_han_solo_young.png" },
  { id: "dlc_chewbacca_young", name: "Chewbacca (Young)", category: "Scoundrel", dlc: "Villains Pack", img: "Character images/dlc_chewbacca_young.png" },
  { id: "dlc_lando_calrissian_young", name: "Lando Calrissian (Young)", category: "Scoundrel", dlc: "Villains Pack", img: "Character images/dlc_lando_calrissian_young.png" },
  { id: "dlc_qira", name: "Qi'ra", category: "Scoundrel", dlc: "Villains Pack", img: "Character images/dlc_qira.png" },
  { id: "dlc_tobias_beckett", name: "Tobias Beckett", category: "Scoundrel", dlc: "Villains Pack", img: "Character images/dlc_tobias_beckett.png" },
  { id: "dlc_enfys_nest", name: "Enfys Nest", category: "Villain", dlc: "Villains Pack", img: "Character images/dlc_enfys_nest.png" },

  // ─── THE MANDALORIAN SEASON 1 PACK ──────────────────────────────────────────
  { id: "dlc_the_mandalorian", name: "The Mandalorian", category: "Bounty Hunter", dlc: "The Mandalorian Season 1 Pack", img: "Character images/dlc_the_mandalorian.png" },
  { id: "dlc_cara_dune", name: "Cara Dune", category: "Hero", dlc: "The Mandalorian Season 1 Pack", img: "Character images/dlc_cara_dune.png" },
  { id: "dlc_greef_karga", name: "Greef Karga", category: "Scoundrel", dlc: "The Mandalorian Season 1 Pack", img: "Character images/dlc_greef_karga.png" },
  { id: "dlc_ig_11", name: "IG-11", category: "Bounty Hunter", dlc: "The Mandalorian Season 1 Pack", img: "Character images/dlc_ig_11.png" },
  { id: "dlc_kuiil", name: "Kuiil", category: "Hero", dlc: "The Mandalorian Season 1 Pack", img: "Character images/dlc_kuiil.png" },

  // ─── THE MANDALORIAN SEASON 2 PACK ──────────────────────────────────────────
  { id: "dlc_ahsoka_tano_mando", name: "Ahsoka Tano (The Mandalorian)", category: "Jedi", dlc: "The Mandalorian Season 2 Pack", img: "Character images/dlc_ahsoka_tano_mando.jpg" },
  { id: "dlc_boba_fett_mando", name: "Boba Fett (Scion of Jango)", category: "Bounty Hunter", dlc: "The Mandalorian Season 2 Pack", img: "Character images/dlc_boba_fett_mando.png" },
  { id: "dlc_bo_katan_kryze", name: "Bo-Katan Kryze", category: "Hero", dlc: "The Mandalorian Season 2 Pack", img: "Character images/dlc_bo_katan_kryze.png" },
  { id: "dlc_fennec_shand", name: "Fennec Shand", category: "Bounty Hunter", dlc: "The Mandalorian Season 2 Pack", img: "Character images/dlc_fennec_shand.png" },
  { id: "dlc_moff_gideon", name: "Moff Gideon", category: "Villain", dlc: "The Mandalorian Season 2 Pack", img: "Character images/dlc_moff_gideon.png" },

  // ─── ROGUE ONE: A STAR WARS STORY PACK ──────────────────────────────────────
  { id: "dlc_jyn_erso", name: "Jyn Erso", category: "Hero", dlc: "Rogue One: A Star Wars Story Pack", img: "Character images/dlc_jyn_erso.png" },
  { id: "dlc_cassian_andor_rogue", name: "Cassian Andor (Rogue One)", category: "Hero", dlc: "Rogue One: A Star Wars Story Pack", img: "Character images/dlc_cassian_andor_rogue.png" },
  { id: "dlc_k_2so", name: "K-2SO", category: "Hero", dlc: "Rogue One: A Star Wars Story Pack", img: "Character images/dlc_k_2so.png" },
  { id: "dlc_bodhi_rook", name: "Bodhi Rook", category: "Hero", dlc: "Rogue One: A Star Wars Story Pack", img: "Character images/dlc_bodhi_rook.png" },
  { id: "dlc_chirrut_imwe", name: "Chirrut Imwe", category: "Hero", dlc: "Rogue One: A Star Wars Story Pack", img: "Character images/dlc_chirrut_imwe.png" },
  { id: "dlc_baze_malbus", name: "Baze Malbus", category: "Hero", dlc: "Rogue One: A Star Wars Story Pack", img: "Character images/dlc_baze_malbus.png" },
  { id: "dlc_director_krennic", name: "Director Krennic", category: "Villain", dlc: "Rogue One: A Star Wars Story Pack", img: "Character images/dlc_director_krennic.png" },

  // ─── BAD BATCH PACK ─────────────────────────────────────────────────────────
  { id: "dlc_hunter", name: "Hunter", category: "Hero", dlc: "Bad Batch Pack", img: "Character images/dlc_hunter.png" },
  { id: "dlc_wrecker", name: "Wrecker", category: "Hero", dlc: "Bad Batch Pack", img: "Character images/dlc_wrecker.png" },
  { id: "dlc_tech", name: "Tech", category: "Hero", dlc: "Bad Batch Pack", img: "Character images/dlc_tech.png" },
  { id: "dlc_crosshair", name: "Crosshair", category: "Villain", dlc: "Bad Batch Pack", img: "Character images/dlc_crosshair.png" },
  { id: "dlc_echo", name: "Echo", category: "Hero", dlc: "Bad Batch Pack", img: "Character images/dlc_echo.png" },

  // ─── LEGO STAR WARS: SUMMER VACATION ────────────────────────────────────────
  { id: "dlc_obi_wan_kenobi_summer", name: "Obi-Wan Kenobi (Summer Vacation)", category: "Jedi", dlc: "LEGO Star Wars: Summer Vacation", img: "Character images/dlc_obi_wan_kenobi_summer.png" },
  { id: "dlc_darth_vader_summer", name: "Darth Vader (Summer Vacation)", category: "Dark Side", dlc: "LEGO Star Wars: Summer Vacation", img: "Character images/dlc_darth_vader_summer.png" },
  { id: "dlc_finn_summer", name: "Finn (Summer Vacation)", category: "Hero", dlc: "LEGO Star Wars: Summer Vacation", img: "Character images/dlc_finn_summer.png" },
  { id: "dlc_darth_sidious_summer", name: "Darth Sidious (Summer Vacation)", category: "Dark Side", dlc: "LEGO Star Wars: Summer Vacation", img: "Character images/dlc_darth_sidious_summer.png" },
  { id: "dlc_r2_d2_summer", name: "R2-D2 (Summer Vacation)", category: "Astromech Droid", dlc: "LEGO Star Wars: Summer Vacation", img: "Character images/dlc_r2_d2_summer.png" },

  // ─── GALACTIC EMPIRE PACK (Obi-Wan Kenobi Series) ───────────────────────────
  { id: "dlc_ben_kenobi_series", name: "Ben Kenobi (Kenobi Series)", category: "Jedi", dlc: "Galactic Empire Pack", img: "Character images/dlc_ben_kenobi_series.png" },
  { id: "dlc_darth_vader_kenobi", name: "Darth Vader (Kenobi Series)", category: "Dark Side", dlc: "Galactic Empire Pack", img: "Character images/dlc_darth_vader_kenobi.png" },
  { id: "dlc_reva_third_sister", name: "Reva (Third Sister)", category: "Dark Side", dlc: "Galactic Empire Pack", img: "Character images/dlc_reva_third_sister.png" },
  { id: "dlc_grand_inquisitor", name: "Grand Inquisitor", category: "Dark Side", dlc: "Galactic Empire Pack", img: "Character images/dlc_grand_inquisitor.png" },
  { id: "dlc_fifth_brother", name: "Fifth Brother", category: "Dark Side", dlc: "Galactic Empire Pack", img: "Character images/dlc_fifth_brother.png" },

  // ─── GHOST CREW PACK (Star Wars: Rebels) ────────────────────────────────────
  { id: "dlc_sabine_wren", name: "Sabine Wren", category: "Hero", dlc: "Ghost Crew Pack", img: "Character images/dlc_sabine_wren.png" },
  { id: "dlc_ezra_bridger", name: "Ezra Bridger", category: "Jedi", dlc: "Ghost Crew Pack", img: "Character images/dlc_ezra_bridger.png" },
  { id: "dlc_admiral_thrawn", name: "Grand Admiral Thrawn", category: "Villain", dlc: "Ghost Crew Pack", img: "Character images/dlc_admiral_thrawn.png" },
  { id: "dlc_kanan_jarrus", name: "Kanan Jarrus", category: "Jedi", dlc: "Ghost Crew Pack", img: "Character images/dlc_kanan_jarrus.png" },
  { id: "dlc_hera_syndulla", name: "Hera Syndulla", category: "Hero", dlc: "Ghost Crew Pack", img: "Character images/dlc_hera_syndulla.png" },

  // ─── AHSOKA CHARACTER PACK (The Clone Wars) ──────────────────────────────────
  { id: "dlc_ahsoka_tano_cw", name: "Ahsoka Tano (The Clone Wars)", category: "Jedi", dlc: "Ahsoka Character Pack", img: "Character images/dlc_ahsoka_tano_cw.png" },
  { id: "dlc_captain_rex", name: "Captain Rex", category: "Hero", dlc: "Ahsoka Character Pack", img: "Character images/dlc_captain_rex.png" },
  { id: "dlc_darth_maul_cw", name: "Darth Maul (The Clone Wars)", category: "Dark Side", dlc: "Ahsoka Character Pack", img: "Character images/dlc_darth_maul_cw.png" },
  { id: "dlc_asajj_ventress", name: "Asajj Ventress", category: "Dark Side", dlc: "Ahsoka Character Pack", img: "Character images/dlc_asajj_ventress.png" },
  { id: "dlc_savage_opress", name: "Savage Opress", category: "Dark Side", dlc: "Ahsoka Character Pack", img: "Character images/dlc_savage_opress.png" },

  // ─── ANDOR PACK ─────────────────────────────────────────────────────────────
  { id: "dlc_cassian_andor", name: "Cassian Andor (Andor)", category: "Hero", dlc: "Andor Pack", img: "Character images/dlc_cassian_andor.png" },
  { id: "dlc_luthen_rael", name: "Luthen Rael", category: "Scoundrel", dlc: "Andor Pack", img: "Character images/dlc_luthen_rael.png" },
  { id: "dlc_syril_karn", name: "Syril Karn", category: "Villain", dlc: "Andor Pack", img: "Character images/dlc_syril_karn.png" },
  { id: "dlc_supervisor_dedra_meero", name: "Supervisor Dedra Meero", category: "Villain", dlc: "Andor Pack", img: "Character images/dlc_supervisor_dedra_meero.png" },
  { id: "dlc_bix_caleen", name: "Bix Caleen", category: "Hero", dlc: "Andor Pack", img: "Character images/dlc_bix_caleen.png" },

  // ─── THE BOOK OF BOBA FETT PACK ─────────────────────────────────────────────
  { id: "dlc_krrsantan", name: "Krrsantan", category: "Bounty Hunter", dlc: "The Book of Boba Fett Pack", img: "Character images/dlc_krrsantan.png" },
  { id: "dlc_cad_bane", name: "Cad Bane", category: "Bounty Hunter", dlc: "The Book of Boba Fett Pack", img: "Character images/dlc_cad_bane.png" },
  { id: "dlc_cobb_vanth", name: "Cobb Vanth", category: "Hero", dlc: "The Book of Boba Fett Pack", img: "Character images/dlc_cobb_vanth.png" },
  { id: "dlc_peli_motto", name: "Peli Motto", category: "Hero", dlc: "The Book of Boba Fett Pack", img: "Character images/dlc_peli_motto.png" },
  { id: "dlc_the_armorer", name: "The Armorer", category: "Hero", dlc: "The Book of Boba Fett Pack", img: "Character images/dlc_the_armorer.png" },
];

