const fs = require('fs');

const BASE_URL = 'https://archive.org/download/ds-store_202204/';

const mapping = {
  // Astromech
  'LEGO Star Wars/Astromech/LSW_ProfileIcons_BB8.png': 'bb_8.png',
  'LEGO Star Wars/Astromech/LSW_ProfileIcons_BB8_Bin.png': 'bb_8_disguise.png',
  'LEGO Star Wars/Astromech/LSW_ProfileIcons_BB9E.png': 'bb_9e.png',
  'LEGO Star Wars/Astromech/LSW_ProfileIcons_G8R3.png': 'g8_r3.png',
  'LEGO Star Wars/Astromech/LSW_ProfileIcons_R2A6.png': 'r2_a6.png',
  'LEGO Star Wars/Astromech/LSW_ProfileIcons_R2B1.png': 'r2_b1.png',
  'LEGO Star Wars/Astromech/LSW_ProfileIcons_R2D2.png': 'r2_d2.png',
  'LEGO Star Wars/Astromech/LSW_ProfileIcons_R2D2_Swamp.png': 'r2_d2_swamp.png',
  'LEGO Star Wars/Astromech/LSW_ProfileIcons_R2D2_Waiter.png': 'r2_d2_waiter.png',
  'LEGO Star Wars/Astromech/LSW_ProfileIcons_R2KT.png': 'r2_kt.png',
  'LEGO Star Wars/Astromech/LSW_ProfileIcons_R2N3.png': 'r2_n3.png',
  'LEGO Star Wars/Astromech/LSW_ProfileIcons_R2Q5.png': 'r2_q5.png',
  'LEGO Star Wars/Astromech/LSW_ProfileIcons_R4P17.png': 'r4_p17.png',
  'LEGO Star Wars/Astromech/LSW_ProfileIcons_R52JE.png': 'r5_2je.png',
  'LEGO Star Wars/Astromech/LSW_ProfileIcons_R5D4.png': 'r5_d4.png',
  'LEGO Star Wars/Astromech/LSW_ProfileIcons_R5M2.png': 'r5_m2.png',
  'LEGO Star Wars/Astromech/LSW_PhotoIcons_R2R9.png': 'r2_r9.png',
  'LEGO Star Wars/Astromech/LSW_PhotoIcons_R4-M9.png': 'r4_m9.png',
  // Bounty Hunter
  'LEGO Star Wars/Bounty Hunter/LSW_ProfileIcons_4Lom.png': '4_lom.png',
  'LEGO Star Wars/Bounty Hunter/LSW_ProfileIcons_AurraSing.png': 'aurra_sing.png',
  'LEGO Star Wars/Bounty Hunter/LSW_PhotoIcons_BazineNetal.png': 'bazine_netal.png',
  'LEGO Star Wars/Bounty Hunter/LSW_ProfileIcons_BobaFett_Skiff.png': 'boba_fett.png',
  'LEGO Star Wars/Bounty Hunter/LSW_PhotoIcons_Dengar.png': 'dengar.png',
  'LEGO Star Wars/Bounty Hunter/LSW_PhotoIcons_Greedo.png': 'greedo.png',
  'LEGO Star Wars/Bounty Hunter/LSW_PhotoIcons_IG-88.png': 'ig_88.png',
  'LEGO Star Wars/Bounty Hunter/LSW_ProfileIcons_JangoFett.png': 'jango_fett.png',
  'LEGO Star Wars/Bounty Hunter/LSW_ProfileIcons_JangoFett_Casual.png': 'jango_fett_casual.png',
  'LEGO Star Wars/Bounty Hunter/LSW_PhotoIcons_Leia_BoushhDisguise.png': 'leia_boussh_disguise.png',
  'LEGO Star Wars/Bounty Hunter/LSW_ProfileIcons_RothgarDeng.png': 'rothgar_deng.png',
  'LEGO Star Wars/Bounty Hunter/LSW_ProfileIcons_ZamWesell_Alien.png': 'zam_wesell_alien.png',
  'LEGO Star Wars/Bounty Hunter/LSW_PhotoIcons_ZamWesell_Human.png': 'zam_wesell_human.png',
  'LEGO Star Wars/Bounty Hunter/LSW_ProfileIcons_Zuckuss.png': 'zuckuss.png',
  'LEGO Star Wars/Bounty Hunter/LSW_ProfileIcons_CaribDiss.png': 'carib_diss.png',
  // Dark Side
  'LEGO Star Wars/Dark Side/LSW_ProfileIcons_Anakin_Burnt.png': 'anakin_skywalker_charred.png',
  'LEGO Star Wars/Dark Side/LSW_PhotoIcons_AnakinSkywalker_YellowEyes.png': 'anakin_skywalker_yellow_eyes.png',
  'LEGO Star Wars/Dark Side/LSW_PhotoIcons_CountDooku.png': 'count_dooku.png',
  'LEGO Star Wars/Dark Side/LSW_ProfileIcons_DarthMaul_Hood.png': 'darth_maul.png',
  'LEGO Star Wars/Dark Side/LSW_PhotoIcons_DarthMaul.png': 'darth_maul_no_cape.png',
  'LEGO Star Wars/Dark Side/LSW_ProfileIcons_DarthVader.png': 'darth_vader.png',
  'LEGO Star Wars/Dark Side/LSW_ProfileIcons_DarthVader_NoHelmet.png': 'darth_vader_no_helmet.png',
  'LEGO Star Wars/Dark Side/LSW_PhotoIcons_KyloRen_ReforgedHelmet.png': 'kylo_ren_ep9.png',
  'LEGO Star Wars/Dark Side/LSW_ProfileIcons_KyloRen_NoHelmet.png': 'kylo_ren_no_helmet.png',
  'LEGO Star Wars/Dark Side/LSW_ProfileIcons_KyloRen_NoHelmet_Scar.png': 'kylo_ren_no_helmet_scar.png',
  'LEGO Star Wars/Dark Side/LSW_PhotoIcons_KyloRen_Topless.png': 'kylo_ren_topless.png',
  'LEGO Star Wars/Dark Side/LSW_ProfileIcons_KyloRen.png': 'kylo_ren.png',
  'LEGO Star Wars/Dark Side/LSW_ProfileIcons_Palpatine_Young_Scarred.png': 'palpatine_scarred.png',
  'LEGO Star Wars/Dark Side/LSW_PhotoIcons_Palpatine_Sheev_Episode2.png': 'palpatine_senator.png',
  'LEGO Star Wars/Dark Side/LSW_ProfileIcons_Palpatine_Grey.png': 'palpatine_chancellor_grey.png',
  'LEGO Star Wars/Dark Side/LSW_ProfileIcons_Palpatine_red.png': 'palpatine_chancellor_red.png',
  'LEGO Star Wars/Dark Side/LSW_ProfileIcons_Rey_Dark_Ep9.png': 'rey_sith.png',
  'LEGO Star Wars/Dark Side/LSW_PhotoIcons_Snoke.png': 'snoke.png',
  'LEGO Star Wars/Dark Side/LSW_ProfileIcons_DarthSidious_Ep9_Reborn.png': 'the_emperor.png',
  // Extras
  'LEGO Star Wars/Extras/LSW_ProfileIcons_21B.png': '2_1b.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_8D8.png': '8d8.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_AD4M.png': 'ad_4m.png',
  'LEGO Star Wars/Extras/LSW_PhotoIcons_Alcida-Auka.png': 'alcida_auka.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_Anakin_Boy.png': 'anakin_skywalker_ep1.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_Anakin_Boy_Starfighter.png': 'anakin_skywalker_pilot.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_BabuFrik.png': 'babu_frik.png',
  'LEGO Star Wars/Extras/LSW_PhotoIcons_BibFortuna.png': 'bib_fortuna.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_BobaFett_Young.png': 'boba_fett_young.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_Bobbajo.png': 'bobbajo.png',
  'LEGO Star Wars/Extras/LSW_PhotoIcons_D-0.png': 'd_0.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_DellsoPrin.png': 'dellso_prin.png',
  'LEGO Star Wars/Extras/LSW_PhotoIcons_DexterJettster.png': 'dexter_jettster.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_Droideka.png': 'droideka.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_EV9D9.png': 'ev_9d9.png',
  "LEGO Star Wars/Extras/LSW_PhotoIcons_FigrinD'an.png": 'figrin_dan.png',
  'LEGO Star Wars/Extras/LSW_PhotoIcons_FodeAndBeed.png': 'fode_and_beed.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_Gasgano.png': 'gasgano.png',
  'LEGO Star Wars/Extras/LSW_PhotoIcons_GonkDroid.png': 'gonk_droid.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_GNK_Sith.png': 'gonkatine.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_GrebeKorona.png': 'grebe_korora.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_GreeataJendowanian.png': 'greeata_jendowanian.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_Grummgar.png': 'grummgar.png',
  'LEGO Star Wars/Extras/LSW_PhotoIcons_HanSolo_Carbonite.png': 'han_solo_carbonite.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_MaagnaGuard.png': 'ig_101_magna_guard.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_Jabba.png': 'jabba_the_hutt.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_JangoFett_Clone.png': 'jango_fett_clone.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_LC24_FireDroid.png': 'lc_24.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_LamaSu.png': 'lama_su.png',
  'LEGO Star Wars/Extras/LSW_PhotoIcons_Lobot.png': 'lobot.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_Luke_AhchTo.png': 'luke_skywalker_old_ahch_to.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_Luke_Old_Raincoat.png': 'luke_skywalker_old_raincoat.png',
  'LEGO Star Wars/Extras/LSW_PhotoIcons_Malakili.png': 'malakili.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_MammaTheHutt.png': 'mama_the_hutt.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_MasAmedda.png': 'mas_amedda.png',
  'LEGO Star Wars/Extras/LSW_PhotoIcons_MasterCodebreaker.png': 'master_codebreaker.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_Mawhonic.png': 'mawhonic.png',
  'LEGO Star Wars/Extras/LSW_PhotoIcons_MaxRebo.png': 'max_rebo.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_MisterBones.png': 'mister_bones.png',
  'LEGO Star Wars/Extras/LSW_PhotoIcons_MouseDroid.png': 'mouse_droid.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_Mustafarian.png': 'mustafarian.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_NambiGhima.png': 'nambi_ghima.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_NuteGunray.png': 'nute_gunray.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_OdyMandrell.png': 'ody_mandrell.png',
  'LEGO Star Wars/Extras/LSW_PhotoIcons_Oola.png': 'oola.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_PitDroid.png': 'pit_droid.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_Poggle.png': 'poggle_the_lesser.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_PraetorianGuard_First.png': 'praetorian_guard_first.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_PraetorianGuard_Seventh.png': 'praetorian_guard_seventh.png',
  'LEGO Star Wars/Extras/LSW_PhotoIcons_QueenAmidala.png': 'queen_amidala.png',
  'LEGO Star Wars/Extras/LSW_PhotoIcons_Rancor.png': 'rancor.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_RattsTyerell.png': 'ratts_tyerell.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_ReeYees.png': 'ree_yees.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_R0GR.png': 'roger.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_RuneHaako.png': 'rune_haako.png',
  'LEGO Star Wars/Extras/LSW_PhotoIcons_SalaciousCrumb.png': 'salacious_crumb.png',
  'LEGO Star Wars/Extras/LSW_PhotoIcons_Sebulba.png': 'sebulba.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_SenateGuard.png': 'senate_guard.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_Shmi.png': 'shmi.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_SithAcolytes.png': 'sith_acolyte.png',
  'LEGO Star Wars/Extras/LSW_PhotoIcons_SithProbeDroid.png': 'sith_probe_droid.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_SySnootles.png': 'sy_snootles.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_TemiriBlagg.png': 'temiri_blagg.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_TionMedon.png': 'tion_medon.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_UbblaMollbro.png': 'ubbla_mollbro.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_Ugnaught_A.png': 'ugnaught.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_UnkarPlutt.png': 'unkar_plutt.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_Wampa.png': 'wampa.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_Watto.png': 'watto.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_Weequay.png': 'weequay.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_WillrowHood.png': 'willrow_hood.png',
  'LEGO Star Wars/Extras/LSW_ProfileIcons_GamorreanGuard.png': 'jubnuk.png',
  // Hero
  'LEGO Star Wars/Hero/LSW_ProfileIcons_AdmiralAckbar.png': 'admiral_ackbar.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_AdmiralHoldo.png': 'admiral_holdo.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_AftabAckbar.png': 'aftab_ackbar.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_BailOrgana.png': 'bail_organa.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_BeaumontKin.png': 'beaumont_kin.png',
  'LEGO Star Wars/Hero/LSW_PhotoIcons_Biggs_Darklighter.png': 'biggs_darklighter.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Boolio.png': 'boolio.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_BossNass.png': 'boss_nass.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_CaiThrenalli.png': 'cai_threnalli.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_CaptainAntilles.png': 'captain_antilles.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_CaptainPanaka.png': 'captain_panaka.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_CaptainTarpals.png': 'captain_tarpals.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_CaptainTypho.png': 'captain_typho.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_CloneTrooper.png': 'clone_trooper_phase1.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_CloneTrooper_Cmd.png': 'clone_trooper_commander.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_CloneTrooper_Cpt.png': 'clone_trooper_captain.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_CloneTrooper_Lt.png': 'clone_trooper_lieutenant.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_CloneTrooper_Sgt.png': 'clone_trooper_sergeant.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_CloneTrooper_Phase2.png': 'clone_trooper_phase2.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_CloneTrooper_Phase2_501st.png': 'clone_trooper_501st.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_CloneTrooper_Phase2_Coruscant_Cutscene.png': 'clone_trooper_coruscant_guard.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_CloneTrooper_Phase2_Utapau.png': 'clone_trooper_212th.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_CloneTrooper_Kashyyyk.png': 'clone_trooper_kashyyyk.png',
  'LEGO Star Wars/Hero/LSW_PhotoIcons_CommanderCody.png': 'commander_cody.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_CommanderDacy.png': 'commander_dacy.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_CommanderGree.png': 'commander_gree.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_ElloAtsy.png': 'ello_asty.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Finn_Bacta_Tape.png': 'finn_bacta_suit.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Finn_Crait.png': 'finn_crait.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Finn_Ep9.png': 'finn_ep9.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Finn_KijimiCoat.png': 'finn_kijimi_coat.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Finn_WhiteShirt.png': 'finn_jacket_white_shirt.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_GarvenDreis.png': 'garven_greis.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_GeneralRieekan.png': 'general_rieekan.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_GeneralRieekan_5_1.png': 'general_rieekan_hoth_hood.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Grakchawwaa.png': 'grakchawwaa.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_GunganWarrior_A.png': 'gungan_warrior.png',
  'LEGO Star Wars/Hero/LSW_PhotoIcons_Jannah.png': 'jannah.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_JarJar.png': 'jar_jar_binks.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_JekPorkins.png': 'jet_porkins.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_JessikaPava.png': 'jess_pava.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_KaydelConnix.png': 'kaydel_connix.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_KaydelConnix_Ep9.png': 'kaydel_connix_ep9.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Leia_General.png': 'general_leia_organa.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Leia_General_Bandaged.png': 'general_leia_organa_bandaged.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Leia_Black.png': 'general_leia_organa_black_robes.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Leia_Silver.png': 'general_leia_organa_silver_robes.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Leia_Princess.png': 'leia_ep4.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Leia_JumpSuit.png': 'leia_jabbas_palace.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Leia_CloudCity.png': 'leia_cloud_city.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Leia_Endor.png': 'leia_endor.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Luke_Tatooine.png': 'luke_skywalker_ep4.png',
  'LEGO Star Wars/Hero/LSW_PhotoIcons_LukeSkywalker_Ceremony.png': 'luke_skywalker_ceremony.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Luke_Pilot.png': 'luke_skywalker_rebel_pilot.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_MonMothma.png': 'mon_mothma.png',
  'LEGO Star Wars/Hero/LSW_PhotoIcons_NienNunb.png': 'nien_nunb.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Padme_Handmaiden_Orange.png': 'padme_handmaiden_orange.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Padme_Handmaiden_Theed.png': 'padme_ship.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Padme_Pilot.png': 'padme_pilot.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Padme_Pilot_Helmet.png': 'padme_pilot_helmet.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Padme_Pregnant.png': 'padme_pregnant.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Padme_SilverCape.png': 'padme_silver_cape.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Padme_Tatooine.png': 'padme_tatooine_disguise.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Padme_White.png': 'padme_battle_of_naboo.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Padme_Clawed.png': 'padme_clawed.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_PoeDameron_BlackJacket.png': 'poe_dameron_black_resistance_jacket.png',
  'LEGO Star Wars/Hero/LSW_PhotoIcons_PoeDameron_Ep9.png': 'poe_dameron_ep9.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_PoeDameron_Jacket.png': 'poe_dameron_jacket.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_PoeDameron_KijimiCoat.png': 'poe_dameron_kijimi_coat.png',
  'LEGO Star Wars/Hero/LSW_PhotoIcons_PoeDameron_Pilot.png': 'poe_dameron_pilot.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Rebel_Friend.png': 'rebel_friend.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_RicOllie.png': 'ric_olie.png',
  'LEGO Star Wars/Hero/LSW_PhotoIcons_RoseTico.png': 'rose_tico.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Rose_Ep9.png': 'rose_tico_ep9.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_TallieLintra.png': 'tallie_lintra.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_Tarfful.png': 'tarfful.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_TemminWexley.png': 'temmin_wexley.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_TheronNett.png': 'theron_nett.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_WedgeAntilles.png': 'wedge_antilles.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_WrobieTyce.png': 'wrobie_tyce.png',
  'LEGO Star Wars/Hero/LSW_ProfileIcons_ZevSenesca.png': 'zev_senesca.png',
  // Jedi
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_Anakin_JediKnight.png': 'anakin_skywalker_ep3.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_Anakin_Padawan.png': 'anakin_skywalker_ep2.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_BarrissOffee.png': 'barriss_offee.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_BenSolo.png': 'ben_solo.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_JediArchiver.png': 'jocasta_nu.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_KiAdiMundi.png': 'ki_adi_mundi.png',
  'LEGO Star Wars/Jedi/LSW_PhotoIcons_KitFisto.png': 'kit_fisto.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_Leia_Ep9_Flashback.png': 'leia_training_flashback.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_Luke_Black.png': 'luke_skywalker_ep6.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_Luke_Crait.png': 'luke_skywalker_old_crait.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_Luke_Ep5_White.png': 'luke_skywalker_ep5_no_jacket.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_Luke_HoodedCape.png': 'luke_skywalker_jabbas_palace.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_Luke_Hoth.png': 'luke_skywalker_hoth.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_Luke_Ep9_Flashback.png': 'luke_skywalker_training_flashback.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_Luke_Training.png': 'luke_skywalker_ep5_jedi.png',
  'LEGO Star Wars/Jedi/LSW_PhotoIcons_LukeSkywalker_Endor.png': 'luke_skywalker_endor.png',
  'LEGO Star Wars/Jedi/LSW_PhotoIcons_LukeSkywalker_OldFlashback.png': 'luke_skywalker_old_flashback.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_Luke_YodaOnBack.png': 'luke_skywalker_yoda_backpack.png',
  'LEGO Star Wars/Jedi/LSW_PhotoIcons_LuminaraUnduli.png': 'luminara_unduli.png',
  'LEGO Star Wars/Jedi/LSW_PhotoIcons_MaceWindu.png': 'mace_windu.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_MaceWindu_Cape.png': 'mace_windu_cape.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_ObiWan_JediKnight.png': 'obi_wan_kenobi_ep3.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_ObiWan_JediKnight_Robe.png': 'obi_wan_kenobi_ep2_robe.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_ObiWan_JediMaster_Cape.png': 'obi_wan_kenobi_ep2.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_ObiWan_Old_Hood.png': 'old_ben_kenobi_tatooine_hood.png',
  'LEGO Star Wars/Jedi/LSW_PhotoIcons_ObiWanKenobi_Old_Tatooine.png': 'old_ben_kenobi_tatooine.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_ObiWan_Padawan.png': 'obi_wan_kenobi_ep1.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_ObiWan_Padawan_NoCape.png': 'obi_wan_kenobi_ep1_no_cape.png',
  'LEGO Star Wars/Jedi/LSW_PhotoIcons_PloKoon.png': 'plo_koon.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_QuiGonJinn_Tatooine.png': 'qui_gon_jinn_cape.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_QuiGonJinn_Tatooine_NoCape.png': 'qui_gon_jinn_tatooine_disguise.png',
  'LEGO Star Wars/Jedi/LSW_PhotoIcons_Rey_KijimiCoat.png': 'rey_kijimi_coat.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_Rey_Jedi_Grey.png': 'rey_grey_jedi_wrap.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_Rey_Skywalker.png': 'rey_skywalker.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_Rey_Vest_Jedi.png': 'rey_ep7_jedi.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_ShaakTi.png': 'shaak_ti.png',
  'LEGO Star Wars/Jedi/LSW_PhotoIcons_Yaddle.png': 'yaddle.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_YaraelPoof.png': 'yarael_poof.png',
  'LEGO Star Wars/Jedi/LSW_ProfileIcons_Yoda.png': 'yoda.png',
  // Protocol
  'LEGO Star Wars/Protocol/LSW_ProfileIcons_C3PO_SilverLeg.png': 'c_3po.png',
  'LEGO Star Wars/Protocol/LSW_ProfileIcons_C3PO_KijimiCoat.png': 'c_3po_kijimi_coat.png',
  'LEGO Star Wars/Protocol/LSW_ProfileIcons_C3PO_NoShell.png': 'c_3po_ep1.png',
  'LEGO Star Wars/Protocol/LSW_ProfileIcons_C3PO_RedArm.png': 'c_3po_red_arm.png',
  'LEGO Star Wars/Protocol/LSW_ProfileIcons_C3PO_RedEyes.png': 'c_3po_red_eyes.png',
  'LEGO Star Wars/Protocol/LSW_ProfileIcons_C3PO_Rusted.png': 'c_3po_rusted.png',
  'LEGO Star Wars/Protocol/LSW_ProfileIcons_E3PO.png': 'e_3po.png',
  'LEGO Star Wars/Protocol/LSW_ProfileIcons_H1NT.png': 'h1_nt.png',
  'LEGO Star Wars/Protocol/LSW_PhotoIcons_K-3PO.png': 'k_3po.png',
  'LEGO Star Wars/Protocol/LSW_ProfileIcons_ME-8D9.png': 'me_8d9.png',
  'LEGO Star Wars/Protocol/LSW_ProfileIcons_R3PO.png': 'r_3po.png',
  'LEGO Star Wars/Protocol/LSW_ProfileIcons_RA7_Green.png': 'ra_7.png',
  'LEGO Star Wars/Protocol/LSW_ProfileIcons_TC14.png': 'tc_14.png',
  // Scavenger
  'LEGO Star Wars/Scavenger/LSW_ProfileIcons_ChiefChirpa.png': 'chief_chirpa.png',
  'LEGO Star Wars/Scavenger/LSW_PhotoIcons_Logray.png': 'logray.png',
  'LEGO Star Wars/Scavenger/LSW_ProfileIcons_Paploo.png': 'paploo.png',
  'LEGO Star Wars/Scavenger/LSW_ProfileIcons_Rey_Starkiller.png': 'rey_ep7_starkiller_base.png',
  'LEGO Star Wars/Scavenger/LSW_PhotoIcons_Rey_ScavengerGreyVest.png': 'rey_scavenger_grey_vest.png',
  'LEGO Star Wars/Scavenger/LSW_ProfileIcons_Teebo.png': 'teebo.png',
  'LEGO Star Wars/Scavenger/LSW_ProfileIcons_Teedo.png': 'teedo.png',
  'LEGO Star Wars/Scavenger/LSW_ProfileIcons_TuskenRaider.png': 'tusken_raider.png',
  'LEGO Star Wars/Scavenger/LSW_ProfileIcons_Wicket.png': 'wicket.png',
  // Scoundrel
  'LEGO Star Wars/Scoundrel/LSW_ProfileIcons_BalaTik.png': 'bala_tik.png',
  'LEGO Star Wars/Scoundrel/LSW_ProfileIcons_chewbacca.png': 'chewbacca.png',
  'LEGO Star Wars/Scoundrel/LSW_ProfileIcons_DJ.png': 'dj.png',
  'LEGO Star Wars/Scoundrel/LSW_ProfileIcons_DoctorEvazan.png': 'doctor_evazan.png',
  'LEGO Star Wars/Scoundrel/LSW_ProfileIcons_HanSolo_Cantina.png': 'han_solo_ep4.png',
  'LEGO Star Wars/Scoundrel/LSW_PhotoIcons_HanSolo_Episode5.png': 'han_solo_ep5.png',
  'LEGO Star Wars/Scoundrel/LSW_ProfileIcons_HanSolo_Endor.png': 'han_solo_endor.png',
  'LEGO Star Wars/Scoundrel/LSW_ProfileIcons_HanSolo_Hoth.png': 'han_solo_hoth.png',
  'LEGO Star Wars/Scoundrel/LSW_ProfileIcons_HanSolo_Hoth_Hood.png': 'han_solo_hoth_hood.png',
  'LEGO Star Wars/Scoundrel/LSW_ProfileIcons_HanSolo_Skiff.png': 'han_solo_carbonite_shirt.png',
  'LEGO Star Wars/Scoundrel/LSW_ProfileIcons_HanSolo_Old.png': 'han_solo_ep7.png',
  'LEGO Star Wars/Scoundrel/LSW_ProfileIcons_Lando_Ep9.png': 'lando_calrissian_ep9.png',
  'LEGO Star Wars/Scoundrel/LSW_ProfileIcons_Lando_HermitUnmasked.png': 'lando_calrissian_hermit.png',
  'LEGO Star Wars/Scoundrel/LSW_ProfileIcons_Lando_Bespin.png': 'lando_calrissian_ep5.png',
  'LEGO Star Wars/Scoundrel/LSW_ProfileIcons_Lando_General.png': 'lando_calrissian_ep6_general.png',
  'LEGO Star Wars/Scoundrel/LSW_ProfileIcons_Lando_HanSolo.png': 'lando_calrissian_han_solos_clothes.png',
  'LEGO Star Wars/Scoundrel/LSW_PhotoIcons_LandoCalrissian_JabbasPalace.png': 'lando_calrissian_jabbas_palace.png',
  'LEGO Star Wars/Scoundrel/LSW_PhotoIcons_MazKanata.png': 'maz_kanata.png',
  'LEGO Star Wars/Scoundrel/LSW_ProfileIcons_PondaBaba.png': 'ponda_baba.png',
  'LEGO Star Wars/Scoundrel/LSW_ProfileIcons_SidonIthano.png': 'sidon_ithano.png',
  'LEGO Star Wars/Scoundrel/LSW_ProfileIcons_TasuLeech.png': 'tasu_leech.png',
  'LEGO Star Wars/Scoundrel/LSW_ProfileIcons_WanderingWookiee.png': 'wandering_wookiee.png',
  'LEGO Star Wars/Scoundrel/LSW_PhotoIcons_ZorriBliss.png': 'zorii_bliss.png',
  // Villain
  'LEGO Star Wars/Villain/LSW_ProfileIcons_KnightOfRen_Aplek.png': 'ap_lek.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_BattleDroid.png': 'b1_battle_droid.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_BattleDroid_Commander.png': 'b1_battle_droid_commander.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_BattleDroid_Geonosis.png': 'b1_battle_droid_geonosis.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_BattleDroid_Heavy.png': 'b1_battle_droid_heavy_assault.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_BattleDroid_Kashyyyk.png': 'b1_battle_droid_kashyyyk.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_BattleDroid_Security.png': 'b1_battle_droid_security.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_CaptainCanady.png': 'captain_canady.png',
  'LEGO Star Wars/Villain/LSW_PhotoIcons_CaptainPeavey.png': 'captain_peavey.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_CaptainPhasma.png': 'captain_phasma.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_KnightOfRen_Cardo.png': 'cardo.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_CommanderJir.png': 'commander_jir.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_DJ_FirstOrder.png': 'dj_first_order.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_Emperors_RoyalGuard.png': 'emperors_royal_guard.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_Empire_Cpt.png': 'empire_captain.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_Finn_FN2187.png': 'finn_fn2187.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_Finn_FN2187_NoHelmet.png': 'finn_fn2187_no_helmet.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_Finn_FirstOrder.png': 'finn_first_order.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_FlameTrooper.png': 'first_order_flametrooper.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_Stormtrooper_FirstOrder_Ep9_Jet_Trooper.png': 'first_order_jet_trooper.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_Goon_Ofc_FsOfficer_A.png': 'first_order_officer.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_Goon_Ofc_FsO_Kijimi_A.png': 'first_order_officer_kijimi.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_SnowTrooper.png': 'first_order_snowtrooper.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_Snowtrooper_FsO_Ep9.png': 'snowtrooper.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_SpecialForcesFighterPilot_FsO.png': 'first_order_special_forces_fighter_pilot.png',
  'LEGO Star Wars/Villain/LSW_PhotoIcons_TIEFighterPilot_FirstOrder.png': 'first_order_tie_fighter_pilot.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_GeneralGrievous.png': 'general_grievous.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_Hux.png': 'general_hux.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_HanSolo_Stormtrooper_B.png': 'han_solo_stormtrooper.png',
  'LEGO Star Wars/Villain/LSW_PhotoIcons_ImperialFleetTrooper.png': 'imperial_fleet_trooper.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_ImperialGunneryTechnician.png': 'imperial_gunnery_technician.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_KnightOfRen_Kuruk.png': 'kuruk.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_Luke_Stormtrooper_B.png': 'luke_skywalker_stormtrooper.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_OOM9.png': '00m_9.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_GeneralPryde.png': 'pryde.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_Rose_FirstOrder.png': 'rose_tico_first_order.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_Sandtrooper.png': 'sandtrooper.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_ScoutTrooper.png': 'scout_trooper.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_ScoutTrooper_Kashyyyk.png': 'scout_trooper_kashyyyk.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_Sithtrooper_Rocket.png': 'sith_jet_trooper.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_Sithtrooper.png': 'sith_trooper.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_SovereignProtector.png': 'sovereign_protector.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_Stormtrooper_Cmd.png': 'stormtrooper_empire_sergeant.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_Stormtrooper.png': 'stormtrooper.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_Stormtrooper_FirstOrder_Cmd.png': 'stormtrooper_empire_commander.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_Stormtrooper_FirstOrder.png': 'stormtrooper_first_order.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_Stormtrooper_FirstOrder_Heavy.png': 'stormtrooper_first_order_heavy_assault.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_TIEfighterPilot.png': 'tie_fighter_pilot.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_Tarkin.png': 'tarkin.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_KnightOfRen_Trudgen.png': 'trudgen.png',
  'LEGO Star Wars/Villain/LSW_PhotoIcons_KnightOfRen_Ushar.png': 'ushar.png',
  'LEGO Star Wars/Villain/LSW_ProfileIcons_KnightOfRen_Vicrul.png': 'vicrul.png',
};

const cmds = [];
for (const [archivePath, localFile] of Object.entries(mapping)) {
  // Encode path segments individually, preserving slashes
  const encodedPath = archivePath.split('/').map(s => encodeURIComponent(s)).join('/');
  const url = BASE_URL + encodedPath;
  const out = `D:/Lego starwars/Character images/${localFile}`;
  cmds.push(`curl -L --max-time 30 --silent --show-error -o "${out}" "${url}"`);
}

fs.writeFileSync('D:/Lego starwars/download_images.sh', cmds.join('\n') + '\n');
console.log('Generated', cmds.length, 'download commands');
